import type { LadderDiagramTheme } from 'ladder-visualizer';

/** All colors are owned by the app CSS and react to light/dark changes in place. */
export const CONTROL_ZEBRA_LADDER_THEME: Required<LadderDiagramTheme> = {
  powerRailColor: 'var(--ladder-power-rail-color)',
  wireColor: 'var(--ladder-wire-color)',
  contactColor: 'var(--ladder-contact-color)',
  contactNCColor: 'var(--ladder-contact-nc-color)',
  coilColor: 'var(--ladder-coil-color)',
  boxBorderColor: 'var(--ladder-box-border-color)',
  boxBgColor: 'var(--ladder-box-bg-color)',
  boxTextColor: 'var(--ladder-box-text-color)',
  rungNumberBg: 'var(--ladder-rung-number-bg)',
  rungNumberColor: 'var(--ladder-rung-number-color)',
  labelColor: 'var(--ladder-label-color)',
  addressColor: 'var(--ladder-address-color)',
  branchConnectorColor: 'var(--ladder-branch-connector-color)',
  energizedColor: 'var(--ladder-energized-color)',
  energizedFill: 'var(--ladder-energized-fill)',
  diffAddedBorderColor: 'var(--ladder-diff-added-border-color)',
  diffAddedFillColor: 'var(--ladder-diff-added-fill-color)',
  diffRemovedBorderColor: 'var(--ladder-diff-removed-border-color)',
  diffRemovedFillColor: 'var(--ladder-diff-removed-fill-color)',
  diffTextModifiedBg: 'var(--ladder-diff-text-modified-bg)',
  diffOldTextColor: 'var(--ladder-diff-old-text-color)',
  diffNewTextColor: 'var(--ladder-diff-new-text-color)',
  diffRungAddedWash: 'var(--ladder-diff-rung-added-wash)',
  diffRungRemovedWash: 'var(--ladder-diff-rung-removed-wash)',
  rowEvenBg: 'var(--lv-bg-row-even)',
  rowOddBg: 'var(--lv-bg-row-odd)',
  cellEvenBg: 'var(--lv-bg-cell-even)',
  cellOddBg: 'var(--lv-bg-cell-odd)',
  bgPrimary: 'var(--lv-bg-primary)',
  borderColor: 'var(--lv-border-default)',
  textMuted: 'var(--lv-text-muted)',
};
