// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileSystemService provides file system operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyToClipboard copies the given text to the system clipboard
 * @param {string} text
 * @returns {$CancellablePromise<$models.OpenFileResult>}
 */
export function CopyToClipboard(text) {
    return $Call.ByID(2069356840, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetParentDirectory returns the parent directory of the given path
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetParentDirectory(path) {
    return $Call.ByID(649918929, path);
}

/**
 * ListDirectory lists the contents of a directory (excludes hidden files by default)
 * @param {string} path
 * @returns {$CancellablePromise<$models.DirectoryContents>}
 */
export function ListDirectory(path) {
    return $Call.ByID(1835098089, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListDirectoryWithOptions lists the contents of a directory with options
 * includeHidden: if true, includes hidden files (starting with .)
 * @param {string} path
 * @param {boolean} includeHidden
 * @returns {$CancellablePromise<$models.DirectoryContents>}
 */
export function ListDirectoryWithOptions(path, includeHidden) {
    return $Call.ByID(1279090861, path, includeHidden).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * OpenFile opens a file with the default application
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenFileResult>}
 */
export function OpenFile(path) {
    return $Call.ByID(2404162648, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenInTerminal opens a terminal at the specified path
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenFileResult>}
 */
export function OpenInTerminal(path) {
    return $Call.ByID(301110197, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RevealInFinder opens the containing folder in the system file manager and selects the file
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenFileResult>}
 */
export function RevealInFinder(path) {
    return $Call.ByID(1552683400, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OpenFileResult.createFrom;
const $$createType1 = $models.DirectoryContents.createFrom;
