// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileWatcherService watches directories for file changes and emits events
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetWatchedPath returns the currently watched path
 * @returns {$CancellablePromise<string>}
 */
export function GetWatchedPath() {
    return $Call.ByID(475360882);
}

/**
 * SetApp sets the Wails application reference for event emission
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(129471496, app);
}

/**
 * StopWatching stops watching the current directory
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StopWatching() {
    return $Call.ByID(4209519710).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * WatchDirectory starts watching a directory for changes
 * Returns an error if the directory cannot be watched
 * @param {string} path
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function WatchDirectory(path) {
    return $Call.ByID(45568873, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
