// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileSystemService provides file system operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetParentDirectory returns the parent directory of the given path
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetParentDirectory(path) {
    return $Call.ByID(649918929, path);
}

/**
 * ListDirectory lists the contents of a directory
 * @param {string} path
 * @returns {$CancellablePromise<$models.DirectoryContents>}
 */
export function ListDirectory(path) {
    return $Call.ByID(1835098089, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenFile opens a file with the default application
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenFileResult>}
 */
export function OpenFile(path) {
    return $Call.ByID(2404162648, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DirectoryContents.createFrom;
const $$createType1 = $models.OpenFileResult.createFrom;
