// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService provides git operations via CLI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortMerge aborts the current merge operation.
 * Returns the repository to the state before the merge started.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function AbortMerge(repoPath) {
    return $Call.ByID(195671387, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Branches returns all branches in the repository
 * Uses concurrent goroutines to fetch current, local, and remote branches in parallel
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.BranchList>}
 */
export function Branches(repoPath) {
    return $Call.ByID(1332778193, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckLockFile checks if a .git/index.lock file exists in the repository.
 * This lock file is created by Git during operations and can be left behind if
 * a process crashes or is interrupted.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LockFileInfo>}
 */
export function CheckLockFile(repoPath) {
    return $Call.ByID(3861435054, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CheckoutBranch switches to an existing branch.
 * Fails if there are uncommitted changes to prevent accidental loss.
 * @param {string} repoPath
 * @param {string} branchName
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function CheckoutBranch(repoPath, branchName) {
    return $Call.ByID(523493657, repoPath, branchName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CommitAll stages all changes and commits with the given message
 * @param {string} repoPath
 * @param {string} message
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function CommitAll(repoPath, message) {
    return $Call.ByID(2550005343, repoPath, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CompleteMerge completes the merge by committing after all conflicts are resolved.
 * @param {string} repoPath
 * @param {string} message
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function CompleteMerge(repoPath, message) {
    return $Call.ByID(1488148514, repoPath, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateBranchAndCheckout creates a new branch and switches to it.
 * Fails if there are uncommitted changes or if the branch name is invalid.
 * @param {string} repoPath
 * @param {string} branchName
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function CreateBranchAndCheckout(repoPath, branchName) {
    return $Call.ByID(820271594, repoPath, branchName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DetectRepo checks if the given path is a git repository
 * @param {string} path
 * @returns {$CancellablePromise<$models.RepoInfo>}
 */
export function DetectRepo(path) {
    return $Call.ByID(2042099950, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DiffCommitFile returns the diff for a specific file in a commit compared to its parent
 * @param {string} repoPath
 * @param {string} hash
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.FileDiff>}
 */
export function DiffCommitFile(repoPath, hash, filePath) {
    return $Call.ByID(2514426657, repoPath, hash, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * DiffCommits returns the diff between two commits for a specific file (or all files if path is empty)
 * @param {string} repoPath
 * @param {string} fromHash
 * @param {string} toHash
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.FileDiff>}
 */
export function DiffCommits(repoPath, fromHash, toHash, filePath) {
    return $Call.ByID(2294437908, repoPath, fromHash, toHash, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * DiffWorking returns the diff of a file in the working tree vs HEAD
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.FileDiff>}
 */
export function DiffWorking(repoPath, filePath) {
    return $Call.ByID(1394051649, repoPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * DiscardAll discards all uncommitted changes in the working directory.
 * This includes modified files, staged changes, and untracked files.
 * Requires confirm=true as a safety measure for destructive operations.
 * @param {string} repoPath
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function DiscardAll(repoPath, confirm) {
    return $Call.ByID(2689509008, repoPath, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DiscardFile discards changes to a specific file.
 * For untracked files, the file is deleted. For tracked files, changes are reverted to HEAD.
 * Requires confirm=true as a safety measure for destructive operations.
 * @param {string} repoPath
 * @param {string} filePath
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function DiscardFile(repoPath, filePath, confirm) {
    return $Call.ByID(1199901871, repoPath, filePath, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetConflictedFiles returns a list of files with merge conflicts.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.ConflictedFile[]>}
 */
export function GetConflictedFiles(repoPath) {
    return $Call.ByID(3264929955, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetGitVersion returns the installed git version.
 * Used to determine feature compatibility (e.g., git restore requires 2.23+).
 * @returns {$CancellablePromise<$models.GitVersion | null>}
 */
export function GetGitVersion() {
    return $Call.ByID(487908903).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetMergeState detects if the repository is in a merge or rebase state.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.MergeState>}
 */
export function GetMergeState(repoPath) {
    return $Call.ByID(477378934, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetProtectedBranches returns the list of protected branch names.
 * Reads from .rewind-logic/config.json in the repo, falls back to defaults.
 * @param {string} repoPath
 * @returns {$CancellablePromise<string[]>}
 */
export function GetProtectedBranches(repoPath) {
    return $Call.ByID(648498583, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetRecentCommits returns recent commits from the repository
 * @param {string} repoPath
 * @param {number} limit
 * @returns {$CancellablePromise<$models.CommitInfo[]>}
 */
export function GetRecentCommits(repoPath, limit) {
    return $Call.ByID(3891673582, repoPath, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetRemoteURL returns the URL of the origin remote, or empty string if not set
 * @param {string} repoPath
 * @returns {$CancellablePromise<string>}
 */
export function GetRemoteURL(repoPath) {
    return $Call.ByID(2508520694, repoPath);
}

/**
 * InitRepo initializes a new Git repository at the given path.
 * Creates the directory if it doesn't exist.
 * Returns an error if the path is already a Git repository.
 * @param {string} path
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function InitRepo(path) {
    return $Call.ByID(1061210595, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * InitRepoWithLFS initializes a new Git repository with LFS enabled.
 * Creates the directory if it doesn't exist, runs git init, then git lfs install.
 * @param {string} path
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function InitRepoWithLFS(path) {
    return $Call.ByID(4162144414, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * IsProtectedBranch checks if the given branch name is in the protected list.
 * Uses the configured list from settings, falling back to defaults.
 * @param {string} repoPath
 * @param {string} branchName
 * @returns {$CancellablePromise<boolean>}
 */
export function IsProtectedBranch(repoPath, branchName) {
    return $Call.ByID(329834213, repoPath, branchName);
}

/**
 * MarkResolved marks a file as resolved after manual editing.
 * Runs: git add <path>
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function MarkResolved(repoPath, filePath) {
    return $Call.ByID(1142993024, repoPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Pull fetches and merges changes from the remote
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function Pull(repoPath) {
    return $Call.ByID(2425239014, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Push pushes local commits to the remote
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function Push(repoPath) {
    return $Call.ByID(3059390037, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RemoveLockFile removes the .git/index.lock file from the repository.
 * This is useful for recovering from a stale lock file left behind by a crashed
 * Git process. Returns an OperationResult indicating success or failure.
 * 
 * CAUTION: Only call this when you are certain no other Git operation is in progress.
 * Removing a lock file while another Git process is running can cause corruption.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RemoveLockFile(repoPath) {
    return $Call.ByID(2787472740, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResetHardHead resets the working directory to HEAD, discarding all uncommitted changes.
 * This is the "Rewind" feature - returns to the last committed state.
 * Requires confirm=true as a safety measure for destructive operations.
 * @param {string} repoPath
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ResetHardHead(repoPath, confirm) {
    return $Call.ByID(3423917539, repoPath, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResetSoftHead undoes the last n commits, keeping changes staged.
 * This is the "Undo Last Save" feature - changes remain in the working directory.
 * Requires confirm=true as a safety measure for destructive operations.
 * @param {string} repoPath
 * @param {number} n
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ResetSoftHead(repoPath, n, confirm) {
    return $Call.ByID(3890315074, repoPath, n, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResolveConflictKeepOurs resolves a conflict by keeping our version.
 * Runs: git checkout --ours <path> && git add <path>
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ResolveConflictKeepOurs(repoPath, filePath) {
    return $Call.ByID(31585627, repoPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResolveConflictKeepTheirs resolves a conflict by keeping their version.
 * Runs: git checkout --theirs <path> && git add <path>
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ResolveConflictKeepTheirs(repoPath, filePath) {
    return $Call.ByID(641756609, repoPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetProtectedBranches updates the list of protected branches for the repo.
 * Stores in .rewind-logic/config.json in the repository.
 * @param {string} repoPath
 * @param {string[]} branches
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function SetProtectedBranches(repoPath, branches) {
    return $Call.ByID(818193003, repoPath, branches).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ShowCommit returns detailed information about a specific commit
 * Uses concurrent goroutines to fetch metadata, numstat, and name-status in parallel
 * @param {string} repoPath
 * @param {string} hash
 * @returns {$CancellablePromise<$models.CommitDetail>}
 */
export function ShowCommit(repoPath, hash) {
    return $Call.ByID(727120561, repoPath, hash).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * StashAndSwitchBranch performs a safe branch switch by stashing changes first.
 * Flow: stash push → checkout (or checkout -b if createNew) → stash pop
 * If the stash pop fails due to conflicts, the stash is preserved.
 * @param {string} repoPath
 * @param {string} targetBranch
 * @param {boolean} createNew
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StashAndSwitchBranch(repoPath, targetBranch, createNew) {
    return $Call.ByID(455916307, repoPath, targetBranch, createNew).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StashDrop removes a specific stash entry by index.
 * Requires confirm=true as a safety measure.
 * @param {string} repoPath
 * @param {number} index
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StashDrop(repoPath, index, confirm) {
    return $Call.ByID(499149391, repoPath, index, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StashList returns all stash entries.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.StashEntry[]>}
 */
export function StashList(repoPath) {
    return $Call.ByID(1662513478, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * StashPop applies the most recent stash and removes it from the stash list.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StashPop(repoPath) {
    return $Call.ByID(1695348217, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StashPush creates a new stash with an optional message.
 * Stashes all tracked changes (staged and unstaged).
 * @param {string} repoPath
 * @param {string} message
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StashPush(repoPath, message) {
    return $Call.ByID(3190282202, repoPath, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Status returns the current status of the repository
 * Uses concurrent goroutines to fetch branch, ahead/behind, and status in parallel
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.RepoStatus>}
 */
export function Status(repoPath) {
    return $Call.ByID(3018306807, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * SupportsRestore returns true if git version supports 'git restore' (2.23+)
 * @returns {$CancellablePromise<boolean>}
 */
export function SupportsRestore() {
    return $Call.ByID(2279015597);
}

/**
 * Sync performs a git pull --rebase followed by git push
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function Sync(repoPath) {
    return $Call.ByID(4020637826, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.BranchList.createFrom;
const $$createType2 = $models.LockFileInfo.createFrom;
const $$createType3 = $models.RepoInfo.createFrom;
const $$createType4 = $models.FileDiff.createFrom;
const $$createType5 = $models.ConflictedFile.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.GitVersion.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.MergeState.createFrom;
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $models.CommitInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.CommitDetail.createFrom;
const $$createType14 = $models.StashEntry.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.RepoStatus.createFrom;
