// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LFSService provides Git LFS operations via CLI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckLocksBeforeBranchSwitch checks for locked LFS files before switching branches.
 * Returns a list of files that are locked by the current user.
 * This is a composite operation for convenience - use GetOwnLocks() directly for more control.
 */
export function CheckLocksBeforeBranchSwitch(repoPath: string): $CancellablePromise<$models.LFSLock[]> {
    return $Call.ByID(4281279413, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FilterLocksByOwner filters a list of locks to only those owned by the specified user.
 * This is a pure function that doesn't make any git calls.
 */
export function FilterLocksByOwner(locks: $models.LFSLock[], owner: string): $CancellablePromise<$models.LFSLock[]> {
    return $Call.ByID(44330752, locks, owner).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetGitUser returns the configured git user name for the repository.
 * This is a standalone operation that can be used independently.
 */
export function GetGitUser(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(433482453, repoPath);
}

/**
 * GetLFSVersion returns the installed git-lfs version
 */
export function GetLFSVersion(): $CancellablePromise<string> {
    return $Call.ByID(3448730039);
}

/**
 * GetOwnLocks returns locks owned by the current git user.
 * This is a composite operation that combines LFSLocks() + GetGitUser() + filtering.
 */
export function GetOwnLocks(repoPath: string): $CancellablePromise<$models.LFSLock[]> {
    return $Call.ByID(2544434162, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetPresetPatterns returns common file patterns for industrial automation files
 */
export function GetPresetPatterns(): $CancellablePromise<$models.PresetPattern[]> {
    return $Call.ByID(3149659634).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTrackedPatterns returns the list of file patterns tracked by Git LFS
 * Parses .gitattributes for entries with filter=lfs
 */
export function GetTrackedPatterns(repoPath: string): $CancellablePromise<$models.TrackedPattern[]> {
    return $Call.ByID(73896211, repoPath).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * InitializeLFS initializes Git LFS for a repository
 * This runs `git lfs install` in the repo context
 */
export function InitializeLFS(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2299931107, repoPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * IsLFSEnabled checks if Git LFS is enabled for a repository
 */
export function IsLFSEnabled(repoPath: string): $CancellablePromise<$models.LFSInfo> {
    return $Call.ByID(2248796470, repoPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * IsLFSInstalled checks if git-lfs is installed on the system.
 * Result is cached after the first check for efficiency.
 */
export function IsLFSInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(480459609);
}

/**
 * LFSEnv returns LFS environment and configuration information.
 * Equivalent to: git lfs env
 */
export function LFSEnv(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(3973494816, repoPath);
}

/**
 * LFSFetch downloads LFS objects for the current ref or specified refs.
 * Equivalent to: git lfs fetch [remote] [refs...]
 */
export function LFSFetch(repoPath: string, remote: string, ...refs: string[]): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2098198991, repoPath, remote, refs).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSFetchAll fetches LFS objects for all refs.
 * Equivalent to: git lfs fetch --all
 */
export function LFSFetchAll(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2107969114, repoPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSLock locks a file to prevent others from modifying it
 */
export function LFSLock(repoPath: string, filePath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3881850238, repoPath, filePath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSLocks returns the list of locked files in the repository
 */
export function LFSLocks(repoPath: string): $CancellablePromise<$models.LFSLock[]> {
    return $Call.ByID(1235608439, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LFSLsFiles lists LFS-tracked files in the repository.
 * Equivalent to: git lfs ls-files
 */
export function LFSLsFiles(repoPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(990183995, repoPath).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * LFSMigrateInfo shows migration info without making changes.
 * Equivalent to: git lfs migrate info
 */
export function LFSMigrateInfo(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(798354298, repoPath);
}

/**
 * LFSPointer shows pointer information for a file.
 * Equivalent to: git lfs pointer --file=<path>
 */
export function LFSPointer(repoPath: string, filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2540847806, repoPath, filePath);
}

/**
 * LFSPrune removes old LFS files from the local cache.
 * Equivalent to: git lfs prune
 */
export function LFSPrune(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2121661795, repoPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSPruneDryRun shows what would be removed by prune without actually removing.
 * Equivalent to: git lfs prune --dry-run
 */
export function LFSPruneDryRun(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(3770905889, repoPath);
}

/**
 * LFSPull downloads LFS objects and checks them out into the working tree.
 * Equivalent to: git lfs pull [remote]
 */
export function LFSPull(repoPath: string, remote: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4084325826, repoPath, remote).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSPush uploads LFS objects to the remote.
 * Equivalent to: git lfs push [remote] [ref]
 */
export function LFSPush(repoPath: string, remote: string, ref: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4045988993, repoPath, remote, ref).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSPushAll uploads all LFS objects for all refs.
 * Equivalent to: git lfs push --all [remote]
 */
export function LFSPushAll(repoPath: string, remote: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(792430584, repoPath, remote).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LFSStatus returns the status of LFS-tracked files in the working directory
 */
export function LFSStatus(repoPath: string): $CancellablePromise<$models.LFSFileStatus[]> {
    return $Call.ByID(1587393747, repoPath).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * LFSUnlock unlocks a file. If force is true, can unlock files locked by others.
 */
export function LFSUnlock(repoPath: string, filePath: string, force: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3255768305, repoPath, filePath, force).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * TrackPattern adds a file pattern to be tracked by Git LFS
 * Runs: git lfs track "<pattern>"
 */
export function TrackPattern(repoPath: string, pattern: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2422692425, repoPath, pattern).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UntrackPattern removes a file pattern from Git LFS tracking
 * Runs: git lfs untrack "<pattern>"
 */
export function UntrackPattern(repoPath: string, pattern: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3286138206, repoPath, pattern).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LFSLock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PresetPattern.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.TrackedPattern.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.OperationResult.createFrom;
const $$createType7 = $models.LFSInfo.createFrom;
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $models.LFSFileStatus.createFrom;
const $$createType10 = $Create.Array($$createType9);
