// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LFSService provides Git LFS operations via CLI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckLocksBeforeBranchSwitch checks for locked LFS files before switching branches.
 * Returns a list of files that are locked by the current user.
 * This is a composite operation for convenience - use GetOwnLocks() directly for more control.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSLock[]>}
 */
export function CheckLocksBeforeBranchSwitch(repoPath) {
    return $Call.ByID(4281279413, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FilterLocksByOwner filters a list of locks to only those owned by the specified user.
 * This is a pure function that doesn't make any git calls.
 * @param {$models.LFSLock[]} locks
 * @param {string} owner
 * @returns {$CancellablePromise<$models.LFSLock[]>}
 */
export function FilterLocksByOwner(locks, owner) {
    return $Call.ByID(44330752, locks, owner).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetGitUser returns the configured git user name for the repository.
 * This is a standalone operation that can be used independently.
 * @param {string} repoPath
 * @returns {$CancellablePromise<string>}
 */
export function GetGitUser(repoPath) {
    return $Call.ByID(433482453, repoPath);
}

/**
 * GetLFSVersion returns the installed git-lfs version
 * @returns {$CancellablePromise<string>}
 */
export function GetLFSVersion() {
    return $Call.ByID(3448730039);
}

/**
 * GetOwnLocks returns locks owned by the current git user.
 * This is a composite operation that combines LFSLocks() + GetGitUser() + filtering.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSLock[]>}
 */
export function GetOwnLocks(repoPath) {
    return $Call.ByID(2544434162, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetPresetPatterns returns common file patterns for industrial automation files
 * @returns {$CancellablePromise<$models.PresetPattern[]>}
 */
export function GetPresetPatterns() {
    return $Call.ByID(3149659634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTrackedPatterns returns the list of file patterns tracked by Git LFS
 * Parses .gitattributes for entries with filter=lfs
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.TrackedPattern[]>}
 */
export function GetTrackedPatterns(repoPath) {
    return $Call.ByID(73896211, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * InitializeLFS initializes Git LFS for a repository
 * This runs `git lfs install` in the repo context
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function InitializeLFS(repoPath) {
    return $Call.ByID(2299931107, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * IsLFSEnabled checks if Git LFS is enabled for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSInfo>}
 */
export function IsLFSEnabled(repoPath) {
    return $Call.ByID(2248796470, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * IsLFSInstalled checks if git-lfs is installed on the system.
 * Result is cached after the first check for efficiency.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLFSInstalled() {
    return $Call.ByID(480459609);
}

/**
 * LFSEnv returns LFS environment and configuration information.
 * Equivalent to: git lfs env
 * @param {string} repoPath
 * @returns {$CancellablePromise<string>}
 */
export function LFSEnv(repoPath) {
    return $Call.ByID(3973494816, repoPath);
}

/**
 * LFSFetch downloads LFS objects for the current ref or specified refs.
 * Equivalent to: git lfs fetch [remote] [refs...]
 * @param {string} repoPath
 * @param {string} remote
 * @param {string[]} refs
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSFetch(repoPath, remote, ...refs) {
    return $Call.ByID(2098198991, repoPath, remote, refs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSFetchAll fetches LFS objects for all refs.
 * Equivalent to: git lfs fetch --all
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSFetchAll(repoPath) {
    return $Call.ByID(2107969114, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSLock locks a file to prevent others from modifying it
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSLock(repoPath, filePath) {
    return $Call.ByID(3881850238, repoPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSLocks returns the list of locked files in the repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSLock[]>}
 */
export function LFSLocks(repoPath) {
    return $Call.ByID(1235608439, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LFSLsFiles lists LFS-tracked files in the repository.
 * Equivalent to: git lfs ls-files
 * @param {string} repoPath
 * @returns {$CancellablePromise<string[]>}
 */
export function LFSLsFiles(repoPath) {
    return $Call.ByID(990183995, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * LFSMigrateInfo shows migration info without making changes.
 * Equivalent to: git lfs migrate info
 * @param {string} repoPath
 * @returns {$CancellablePromise<string>}
 */
export function LFSMigrateInfo(repoPath) {
    return $Call.ByID(798354298, repoPath);
}

/**
 * LFSPointer shows pointer information for a file.
 * Equivalent to: git lfs pointer --file=<path>
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function LFSPointer(repoPath, filePath) {
    return $Call.ByID(2540847806, repoPath, filePath);
}

/**
 * LFSPrune removes old LFS files from the local cache.
 * Equivalent to: git lfs prune
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSPrune(repoPath) {
    return $Call.ByID(2121661795, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSPruneDryRun shows what would be removed by prune without actually removing.
 * Equivalent to: git lfs prune --dry-run
 * @param {string} repoPath
 * @returns {$CancellablePromise<string>}
 */
export function LFSPruneDryRun(repoPath) {
    return $Call.ByID(3770905889, repoPath);
}

/**
 * LFSPull downloads LFS objects and checks them out into the working tree.
 * Equivalent to: git lfs pull [remote]
 * @param {string} repoPath
 * @param {string} remote
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSPull(repoPath, remote) {
    return $Call.ByID(4084325826, repoPath, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSPush uploads LFS objects to the remote.
 * Equivalent to: git lfs push [remote] [ref]
 * @param {string} repoPath
 * @param {string} remote
 * @param {string} ref
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSPush(repoPath, remote, ref) {
    return $Call.ByID(4045988993, repoPath, remote, ref).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSPushAll uploads all LFS objects for all refs.
 * Equivalent to: git lfs push --all [remote]
 * @param {string} repoPath
 * @param {string} remote
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSPushAll(repoPath, remote) {
    return $Call.ByID(792430584, repoPath, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSStatus returns the status of LFS-tracked files in the working directory
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSFileStatus[]>}
 */
export function LFSStatus(repoPath) {
    return $Call.ByID(1587393747, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * LFSUnlock unlocks a file. If force is true, can unlock files locked by others.
 * @param {string} repoPath
 * @param {string} filePath
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSUnlock(repoPath, filePath, force) {
    return $Call.ByID(3255768305, repoPath, filePath, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * TrackPattern adds a file pattern to be tracked by Git LFS
 * Runs: git lfs track "<pattern>"
 * @param {string} repoPath
 * @param {string} pattern
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function TrackPattern(repoPath, pattern) {
    return $Call.ByID(2422692425, repoPath, pattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * UntrackPattern removes a file pattern from Git LFS tracking
 * Runs: git lfs untrack "<pattern>"
 * @param {string} repoPath
 * @param {string} pattern
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UntrackPattern(repoPath, pattern) {
    return $Call.ByID(3286138206, repoPath, pattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LFSLock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PresetPattern.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.TrackedPattern.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.OperationResult.createFrom;
const $$createType7 = $models.LFSInfo.createFrom;
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $models.LFSFileStatus.createFrom;
const $$createType10 = $Create.Array($$createType9);
