// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LFSService provides Git LFS operations via CLI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckLocksBeforeBranchSwitch checks for locked LFS files before switching branches.
 * Returns a list of files that are locked by the current user.
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSLock[]>}
 */
export function CheckLocksBeforeBranchSwitch(repoPath) {
    return $Call.ByID(4281279413, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLFSVersion returns the installed git-lfs version
 * @returns {$CancellablePromise<string>}
 */
export function GetLFSVersion() {
    return $Call.ByID(3448730039);
}

/**
 * GetPresetPatterns returns common file patterns for industrial automation files
 * @returns {$CancellablePromise<$models.PresetPattern[]>}
 */
export function GetPresetPatterns() {
    return $Call.ByID(3149659634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTrackedPatterns returns the list of file patterns tracked by Git LFS
 * Parses .gitattributes for entries with filter=lfs
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.TrackedPattern[]>}
 */
export function GetTrackedPatterns(repoPath) {
    return $Call.ByID(73896211, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * InitializeLFS initializes Git LFS for a repository
 * This runs `git lfs install` in the repo context
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function InitializeLFS(repoPath) {
    return $Call.ByID(2299931107, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * IsLFSEnabled checks if Git LFS is enabled for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSInfo>}
 */
export function IsLFSEnabled(repoPath) {
    return $Call.ByID(2248796470, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * IsLFSInstalled checks if git-lfs is installed on the system.
 * Result is cached after the first check for efficiency.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLFSInstalled() {
    return $Call.ByID(480459609);
}

/**
 * LFSLock locks a file to prevent others from modifying it
 * @param {string} repoPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSLock(repoPath, filePath) {
    return $Call.ByID(3881850238, repoPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LFSLocks returns the list of locked files in the repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSLock[]>}
 */
export function LFSLocks(repoPath) {
    return $Call.ByID(1235608439, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LFSStatus returns the status of LFS-tracked files in the working directory
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.LFSFileStatus[]>}
 */
export function LFSStatus(repoPath) {
    return $Call.ByID(1587393747, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * LFSUnlock unlocks a file. If force is true, can unlock files locked by others.
 * @param {string} repoPath
 * @param {string} filePath
 * @param {boolean} force
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function LFSUnlock(repoPath, filePath, force) {
    return $Call.ByID(3255768305, repoPath, filePath, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * TrackPattern adds a file pattern to be tracked by Git LFS
 * Runs: git lfs track "<pattern>"
 * @param {string} repoPath
 * @param {string} pattern
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function TrackPattern(repoPath, pattern) {
    return $Call.ByID(2422692425, repoPath, pattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * UntrackPattern removes a file pattern from Git LFS tracking
 * Runs: git lfs untrack "<pattern>"
 * @param {string} repoPath
 * @param {string} pattern
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UntrackPattern(repoPath, pattern) {
    return $Call.ByID(3286138206, repoPath, pattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LFSLock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PresetPattern.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.TrackedPattern.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.OperationResult.createFrom;
const $$createType7 = $models.LFSInfo.createFrom;
const $$createType8 = $models.LFSFileStatus.createFrom;
const $$createType9 = $Create.Array($$createType8);
