// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings contains application preferences
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("lastRepoPath" in $$source)) {
            /**
             * Last opened repository path
             * @member
             * @type {string}
             */
            this["lastRepoPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * BranchConflictCheckResult contains the result of checking for conflicts between branches
 */
export class BranchConflictCheckResult {
    /**
     * Creates a new BranchConflictCheckResult instance.
     * @param {Partial<BranchConflictCheckResult>} [$$source = {}] - The source object to create the BranchConflictCheckResult.
     */
    constructor($$source = {}) {
        if (!("hasConflicts" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasConflicts"] = false;
        }
        if (!("conflictedFiles" in $$source)) {
            /**
             * @member
             * @type {ConflictedFile[]}
             */
            this["conflictedFiles"] = [];
        }
        if (!("parentBranch" in $$source)) {
            /**
             * The parent branch used for checking
             * @member
             * @type {string}
             */
            this["parentBranch"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchConflictCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchConflictCheckResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflictedFiles" in $$parsedSource) {
            $$parsedSource["conflictedFiles"] = $$createField1_0($$parsedSource["conflictedFiles"]);
        }
        return new BranchConflictCheckResult(/** @type {Partial<BranchConflictCheckResult>} */($$parsedSource));
    }
}

/**
 * BranchInfo represents a git branch
 */
export class BranchInfo {
    /**
     * Creates a new BranchInfo instance.
     * @param {Partial<BranchInfo>} [$$source = {}] - The source object to create the BranchInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isCurrent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCurrent"] = false;
        }
        if (!("isRemote" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRemote"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Remote tracking branch
             * @member
             * @type {string | undefined}
             */
            this["upstream"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo(/** @type {Partial<BranchInfo>} */($$parsedSource));
    }
}

/**
 * BranchList contains all branches in a repository
 */
export class BranchList {
    /**
     * Creates a new BranchList instance.
     * @param {Partial<BranchList>} [$$source = {}] - The source object to create the BranchList.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("local" in $$source)) {
            /**
             * @member
             * @type {BranchInfo[]}
             */
            this["local"] = [];
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {BranchInfo[]}
             */
            this["remote"] = [];
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchList}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField1_0($$parsedSource["local"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField2_0($$parsedSource["remote"]);
        }
        return new BranchList(/** @type {Partial<BranchList>} */($$parsedSource));
    }
}

/**
 * CommitDetail contains detailed information about a single commit
 */
export class CommitDetail {
    /**
     * Creates a new CommitDetail instance.
     * @param {Partial<CommitDetail>} [$$source = {}] - The source object to create the CommitDetail.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Full commit message body
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativeDate"] = "";
        }
        if (!("parentHashes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["parentHashes"] = [];
        }
        if (!("files" in $$source)) {
            /**
             * Files changed in this commit
             * @member
             * @type {CommitFileInfo[]}
             */
            this["files"] = [];
        }
        if (!("stats" in $$source)) {
            /**
             * Overall stats
             * @member
             * @type {CommitStats}
             */
            this["stats"] = (new CommitStats());
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitDetail}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        const $$createField10_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parentHashes" in $$parsedSource) {
            $$parsedSource["parentHashes"] = $$createField8_0($$parsedSource["parentHashes"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField9_0($$parsedSource["files"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField10_0($$parsedSource["stats"]);
        }
        return new CommitDetail(/** @type {Partial<CommitDetail>} */($$parsedSource));
    }
}

/**
 * CommitFileInfo represents a file changed in a commit
 */
export class CommitFileInfo {
    /**
     * Creates a new CommitFileInfo instance.
     * @param {Partial<CommitFileInfo>} [$$source = {}] - The source object to create the CommitFileInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * For renames
             * @member
             * @type {string | undefined}
             */
            this["oldPath"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("additions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitFileInfo(/** @type {Partial<CommitFileInfo>} */($$parsedSource));
    }
}

/**
 * CommitInfo represents a single commit
 */
export class CommitInfo {
    /**
     * Creates a new CommitInfo instance.
     * @param {Partial<CommitInfo>} [$$source = {}] - The source object to create the CommitInfo.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativeDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo(/** @type {Partial<CommitInfo>} */($$parsedSource));
    }
}

/**
 * CommitStats contains overall statistics for a commit
 */
export class CommitStats {
    /**
     * Creates a new CommitStats instance.
     * @param {Partial<CommitStats>} [$$source = {}] - The source object to create the CommitStats.
     */
    constructor($$source = {}) {
        if (!("filesChanged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesChanged"] = 0;
        }
        if (!("additions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitStats(/** @type {Partial<CommitStats>} */($$parsedSource));
    }
}

/**
 * ConflictedFile represents a file with merge conflicts
 */
export class ConflictedFile {
    /**
     * Creates a new ConflictedFile instance.
     * @param {Partial<ConflictedFile>} [$$source = {}] - The source object to create the ConflictedFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "both-modified", "deleted-by-us", "deleted-by-them", "both-added"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictedFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictedFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictedFile(/** @type {Partial<ConflictedFile>} */($$parsedSource));
    }
}

/**
 * CustomLFSGroup represents a user-defined LFS extension group
 */
export class CustomLFSGroup {
    /**
     * Creates a new CustomLFSGroup instance.
     * @param {Partial<CustomLFSGroup>} [$$source = {}] - The source object to create the CustomLFSGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * Tailwind color class like "text-cyan-400"
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("extensions" in $$source)) {
            /**
             * e.g., [".bin", ".dat"]
             * @member
             * @type {string[]}
             */
            this["extensions"] = [];
        }
        if (!("description" in $$source)) {
            /**
             * Optional description
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomLFSGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CustomLFSGroup}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField3_0($$parsedSource["extensions"]);
        }
        return new CustomLFSGroup(/** @type {Partial<CustomLFSGroup>} */($$parsedSource));
    }
}

/**
 * CustomLFSGroupsData contains all custom LFS groups
 */
export class CustomLFSGroupsData {
    /**
     * Creates a new CustomLFSGroupsData instance.
     * @param {Partial<CustomLFSGroupsData>} [$$source = {}] - The source object to create the CustomLFSGroupsData.
     */
    constructor($$source = {}) {
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {CustomLFSGroup[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomLFSGroupsData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CustomLFSGroupsData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        return new CustomLFSGroupsData(/** @type {Partial<CustomLFSGroupsData>} */($$parsedSource));
    }
}

/**
 * DirectoryContents contains the contents of a directory
 */
export class DirectoryContents {
    /**
     * Creates a new DirectoryContents instance.
     * @param {Partial<DirectoryContents>} [$$source = {}] - The source object to create the DirectoryContents.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {FileEntry[]}
             */
            this["entries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryContents instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryContents}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new DirectoryContents(/** @type {Partial<DirectoryContents>} */($$parsedSource));
    }
}

/**
 * ExportLFSGroupsResult contains the result of an export operation
 */
export class ExportLFSGroupsResult {
    /**
     * Creates a new ExportLFSGroupsResult instance.
     * @param {Partial<ExportLFSGroupsResult>} [$$source = {}] - The source object to create the ExportLFSGroupsResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportLFSGroupsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportLFSGroupsResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportLFSGroupsResult(/** @type {Partial<ExportLFSGroupsResult>} */($$parsedSource));
    }
}

/**
 * FileEntry represents a file or directory in the file system
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDirectory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDirectory"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("extension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extension"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}

/**
 * FileStatus represents the status of a changed file
 */
export class FileStatus {
    /**
     * Creates a new FileStatus instance.
     * @param {Partial<FileStatus>} [$$source = {}] - The source object to create the FileStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed", "untracked"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStatus(/** @type {Partial<FileStatus>} */($$parsedSource));
    }
}

/**
 * GitVersion represents parsed git version
 */
export class GitVersion {
    /**
     * Creates a new GitVersion instance.
     * @param {Partial<GitVersion>} [$$source = {}] - The source object to create the GitVersion.
     */
    constructor($$source = {}) {
        if (!("Major" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Major"] = 0;
        }
        if (!("Minor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Minor"] = 0;
        }
        if (!("Patch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Patch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitVersion(/** @type {Partial<GitVersion>} */($$parsedSource));
    }
}

/**
 * ImportLFSGroupsResult contains the result of an import operation
 */
export class ImportLFSGroupsResult {
    /**
     * Creates a new ImportLFSGroupsResult instance.
     * @param {Partial<ImportLFSGroupsResult>} [$$source = {}] - The source object to create the ImportLFSGroupsResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("importedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["importedCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportLFSGroupsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportLFSGroupsResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportLFSGroupsResult(/** @type {Partial<ImportLFSGroupsResult>} */($$parsedSource));
    }
}

/**
 * LFSFileStatus represents the LFS status of a file
 */
export class LFSFileStatus {
    /**
     * Creates a new LFSFileStatus instance.
     * @param {Partial<LFSFileStatus>} [$$source = {}] - The source object to create the LFSFileStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "lfs" for LFS-tracked, "git" for regular
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * Human-readable size
             * @member
             * @type {string}
             */
            this["size"] = "";
        }
        if (!("uploaded" in $$source)) {
            /**
             * True if file is uploaded to remote
             * @member
             * @type {boolean}
             */
            this["uploaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSFileStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LFSFileStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSFileStatus(/** @type {Partial<LFSFileStatus>} */($$parsedSource));
    }
}

/**
 * LFSInfo contains basic information about LFS status in a repo
 */
export class LFSInfo {
    /**
     * Creates a new LFSInfo instance.
     * @param {Partial<LFSInfo>} [$$source = {}] - The source object to create the LFSInfo.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LFSInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSInfo(/** @type {Partial<LFSInfo>} */($$parsedSource));
    }
}

/**
 * LFSLock represents a locked file in Git LFS
 */
export class LFSLock {
    /**
     * Creates a new LFSLock instance.
     * @param {Partial<LFSLock>} [$$source = {}] - The source object to create the LFSLock.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("owner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("locked" in $$source)) {
            /**
             * Timestamp
             * @member
             * @type {string}
             */
            this["locked"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSLock instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LFSLock}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSLock(/** @type {Partial<LFSLock>} */($$parsedSource));
    }
}

/**
 * LockFileInfo contains information about Git lock files in the repository
 */
export class LockFileInfo {
    /**
     * Creates a new LockFileInfo instance.
     * @param {Partial<LockFileInfo>} [$$source = {}] - The source object to create the LockFileInfo.
     */
    constructor($$source = {}) {
        if (!("indexLockExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["indexLockExists"] = false;
        }
        if (!("indexLockPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["indexLockPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LockFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LockFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LockFileInfo(/** @type {Partial<LockFileInfo>} */($$parsedSource));
    }
}

/**
 * MergeState represents the current merge/rebase state of a repository
 */
export class MergeState {
    /**
     * Creates a new MergeState instance.
     * @param {Partial<MergeState>} [$$source = {}] - The source object to create the MergeState.
     */
    constructor($$source = {}) {
        if (!("inMerge" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inMerge"] = false;
        }
        if (!("inRebase" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inRebase"] = false;
        }
        if (!("hasConflicts" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasConflicts"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Merge commit message if available
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeState(/** @type {Partial<MergeState>} */($$parsedSource));
    }
}

/**
 * OpenFileResult contains the result of opening a file
 */
export class OpenFileResult {
    /**
     * Creates a new OpenFileResult instance.
     * @param {Partial<OpenFileResult>} [$$source = {}] - The source object to create the OpenFileResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFileResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileResult(/** @type {Partial<OpenFileResult>} */($$parsedSource));
    }
}

/**
 * OpenFolderDialogResult contains the result of an open folder dialog
 */
export class OpenFolderDialogResult {
    /**
     * Creates a new OpenFolderDialogResult instance.
     * @param {Partial<OpenFolderDialogResult>} [$$source = {}] - The source object to create the OpenFolderDialogResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["selected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFolderDialogResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFolderDialogResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFolderDialogResult(/** @type {Partial<OpenFolderDialogResult>} */($$parsedSource));
    }
}

/**
 * OperationResult represents the result of a git operation
 */
export class OperationResult {
    /**
     * Creates a new OperationResult instance.
     * @param {Partial<OperationResult>} [$$source = {}] - The source object to create the OperationResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OperationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationResult(/** @type {Partial<OperationResult>} */($$parsedSource));
    }
}

/**
 * ParentBranchResult contains the detected parent branch information
 */
export class ParentBranchResult {
    /**
     * Creates a new ParentBranchResult instance.
     * @param {Partial<ParentBranchResult>} [$$source = {}] - The source object to create the ParentBranchResult.
     */
    constructor($$source = {}) {
        if (!("parentBranch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentBranch"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "upstream", "merge-base", "default", or "none"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParentBranchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParentBranchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParentBranchResult(/** @type {Partial<ParentBranchResult>} */($$parsedSource));
    }
}

/**
 * PresetPattern represents a preset LFS tracking pattern
 */
export class PresetPattern {
    /**
     * Creates a new PresetPattern instance.
     * @param {Partial<PresetPattern>} [$$source = {}] - The source object to create the PresetPattern.
     */
    constructor($$source = {}) {
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * e.g., "industrial", "media", "documents"
             * @member
             * @type {string}
             */
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetPattern instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetPattern}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetPattern(/** @type {Partial<PresetPattern>} */($$parsedSource));
    }
}

/**
 * RawDiffResult contains raw unified diff text for react-diff-view parsing
 */
export class RawDiffResult {
    /**
     * Creates a new RawDiffResult instance.
     * @param {Partial<RawDiffResult>} [$$source = {}] - The source object to create the RawDiffResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["oldPath"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("binary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binary"] = false;
        }
        if (!("rawDiff" in $$source)) {
            /**
             * Raw unified diff text
             * @member
             * @type {string}
             */
            this["rawDiff"] = "";
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RawDiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RawDiffResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RawDiffResult(/** @type {Partial<RawDiffResult>} */($$parsedSource));
    }
}

/**
 * RepoInfo contains basic information about a git repository
 */
export class RepoInfo {
    /**
     * Creates a new RepoInfo instance.
     * @param {Partial<RepoInfo>} [$$source = {}] - The source object to create the RepoInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoInfo(/** @type {Partial<RepoInfo>} */($$parsedSource));
    }
}

/**
 * RepoStatus contains the current state of a repository
 */
export class RepoStatus {
    /**
     * Creates a new RepoStatus instance.
     * @param {Partial<RepoStatus>} [$$source = {}] - The source object to create the RepoStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("ahead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }
        if (!("changedFiles" in $$source)) {
            /**
             * @member
             * @type {FileStatus[]}
             */
            this["changedFiles"] = [];
        }
        if (!("hasChanges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasChanges"] = false;
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changedFiles" in $$parsedSource) {
            $$parsedSource["changedFiles"] = $$createField3_0($$parsedSource["changedFiles"]);
        }
        return new RepoStatus(/** @type {Partial<RepoStatus>} */($$parsedSource));
    }
}

/**
 * StashEntry represents a single stash entry
 */
export class StashEntry {
    /**
     * Creates a new StashEntry instance.
     * @param {Partial<StashEntry>} [$$source = {}] - The source object to create the StashEntry.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * e.g., "stash@{0}"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * Stash message
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * Branch the stash was created on
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StashEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StashEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StashEntry(/** @type {Partial<StashEntry>} */($$parsedSource));
    }
}

/**
 * TerminalResult contains the result of terminal operations
 */
export class TerminalResult {
    /**
     * Creates a new TerminalResult instance.
     * @param {Partial<TerminalResult>} [$$source = {}] - The source object to create the TerminalResult.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalResult(/** @type {Partial<TerminalResult>} */($$parsedSource));
    }
}

/**
 * TrackedPattern represents a pattern tracked by Git LFS
 */
export class TrackedPattern {
    /**
     * Creates a new TrackedPattern instance.
     * @param {Partial<TrackedPattern>} [$$source = {}] - The source object to create the TrackedPattern.
     */
    constructor($$source = {}) {
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * e.g., "filter=lfs diff=lfs merge=lfs -text"
             * @member
             * @type {string | undefined}
             */
            this["attributes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackedPattern instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrackedPattern}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackedPattern(/** @type {Partial<TrackedPattern>} */($$parsedSource));
    }
}

/**
 * UserProfile contains git user configuration
 */
export class UserProfile {
    /**
     * Creates a new UserProfile instance.
     * @param {Partial<UserProfile>} [$$source = {}] - The source object to create the UserProfile.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile(/** @type {Partial<UserProfile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ConflictedFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BranchInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = CommitFileInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = CommitStats.createFrom;
const $$createType8 = CustomLFSGroup.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = FileEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = FileStatus.createFrom;
const $$createType13 = $Create.Array($$createType12);
