// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings contains application preferences
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("lastRepoPath" in $$source)) {
            /**
             * Last opened repository path
             * @member
             * @type {string}
             */
            this["lastRepoPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * CommitInfo represents a single commit
 */
export class CommitInfo {
    /**
     * Creates a new CommitInfo instance.
     * @param {Partial<CommitInfo>} [$$source = {}] - The source object to create the CommitInfo.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativeDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo(/** @type {Partial<CommitInfo>} */($$parsedSource));
    }
}

/**
 * DirectoryContents contains the contents of a directory
 */
export class DirectoryContents {
    /**
     * Creates a new DirectoryContents instance.
     * @param {Partial<DirectoryContents>} [$$source = {}] - The source object to create the DirectoryContents.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {FileEntry[]}
             */
            this["entries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryContents instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryContents}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new DirectoryContents(/** @type {Partial<DirectoryContents>} */($$parsedSource));
    }
}

/**
 * FileEntry represents a file or directory in the file system
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDirectory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDirectory"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("extension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extension"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}

/**
 * FileStatus represents the status of a changed file
 */
export class FileStatus {
    /**
     * Creates a new FileStatus instance.
     * @param {Partial<FileStatus>} [$$source = {}] - The source object to create the FileStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed", "untracked"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStatus(/** @type {Partial<FileStatus>} */($$parsedSource));
    }
}

/**
 * OpenFileResult contains the result of opening a file
 */
export class OpenFileResult {
    /**
     * Creates a new OpenFileResult instance.
     * @param {Partial<OpenFileResult>} [$$source = {}] - The source object to create the OpenFileResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFileResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileResult(/** @type {Partial<OpenFileResult>} */($$parsedSource));
    }
}

/**
 * OpenFolderDialogResult contains the result of an open folder dialog
 */
export class OpenFolderDialogResult {
    /**
     * Creates a new OpenFolderDialogResult instance.
     * @param {Partial<OpenFolderDialogResult>} [$$source = {}] - The source object to create the OpenFolderDialogResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["selected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFolderDialogResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFolderDialogResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFolderDialogResult(/** @type {Partial<OpenFolderDialogResult>} */($$parsedSource));
    }
}

/**
 * OperationResult represents the result of a git operation
 */
export class OperationResult {
    /**
     * Creates a new OperationResult instance.
     * @param {Partial<OperationResult>} [$$source = {}] - The source object to create the OperationResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OperationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationResult(/** @type {Partial<OperationResult>} */($$parsedSource));
    }
}

/**
 * RepoInfo contains basic information about a git repository
 */
export class RepoInfo {
    /**
     * Creates a new RepoInfo instance.
     * @param {Partial<RepoInfo>} [$$source = {}] - The source object to create the RepoInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoInfo(/** @type {Partial<RepoInfo>} */($$parsedSource));
    }
}

/**
 * RepoStatus contains the current state of a repository
 */
export class RepoStatus {
    /**
     * Creates a new RepoStatus instance.
     * @param {Partial<RepoStatus>} [$$source = {}] - The source object to create the RepoStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("ahead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }
        if (!("changedFiles" in $$source)) {
            /**
             * @member
             * @type {FileStatus[]}
             */
            this["changedFiles"] = [];
        }
        if (!("hasChanges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasChanges"] = false;
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changedFiles" in $$parsedSource) {
            $$parsedSource["changedFiles"] = $$createField3_0($$parsedSource["changedFiles"]);
        }
        return new RepoStatus(/** @type {Partial<RepoStatus>} */($$parsedSource));
    }
}

/**
 * TerminalResult contains the result of terminal operations
 */
export class TerminalResult {
    /**
     * Creates a new TerminalResult instance.
     * @param {Partial<TerminalResult>} [$$source = {}] - The source object to create the TerminalResult.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalResult(/** @type {Partial<TerminalResult>} */($$parsedSource));
    }
}

/**
 * UserProfile contains git user configuration
 */
export class UserProfile {
    /**
     * Creates a new UserProfile instance.
     * @param {Partial<UserProfile>} [$$source = {}] - The source object to create the UserProfile.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile(/** @type {Partial<UserProfile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FileStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
