// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings contains application preferences
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("lastRepoPath" in $$source)) {
            /**
             * Last opened repository path
             * @member
             * @type {string}
             */
            this["lastRepoPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * BranchInfo represents a git branch
 */
export class BranchInfo {
    /**
     * Creates a new BranchInfo instance.
     * @param {Partial<BranchInfo>} [$$source = {}] - The source object to create the BranchInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isCurrent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCurrent"] = false;
        }
        if (!("isRemote" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRemote"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Remote tracking branch
             * @member
             * @type {string | undefined}
             */
            this["upstream"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo(/** @type {Partial<BranchInfo>} */($$parsedSource));
    }
}

/**
 * BranchList contains all branches in a repository
 */
export class BranchList {
    /**
     * Creates a new BranchList instance.
     * @param {Partial<BranchList>} [$$source = {}] - The source object to create the BranchList.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("local" in $$source)) {
            /**
             * @member
             * @type {BranchInfo[]}
             */
            this["local"] = [];
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {BranchInfo[]}
             */
            this["remote"] = [];
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchList}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField1_0($$parsedSource["local"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField2_0($$parsedSource["remote"]);
        }
        return new BranchList(/** @type {Partial<BranchList>} */($$parsedSource));
    }
}

/**
 * CommitDetail contains detailed information about a single commit
 */
export class CommitDetail {
    /**
     * Creates a new CommitDetail instance.
     * @param {Partial<CommitDetail>} [$$source = {}] - The source object to create the CommitDetail.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Full commit message body
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativeDate"] = "";
        }
        if (!("parentHashes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["parentHashes"] = [];
        }
        if (!("files" in $$source)) {
            /**
             * Files changed in this commit
             * @member
             * @type {CommitFileInfo[]}
             */
            this["files"] = [];
        }
        if (!("stats" in $$source)) {
            /**
             * Overall stats
             * @member
             * @type {CommitStats}
             */
            this["stats"] = (new CommitStats());
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitDetail}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parentHashes" in $$parsedSource) {
            $$parsedSource["parentHashes"] = $$createField8_0($$parsedSource["parentHashes"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField9_0($$parsedSource["files"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField10_0($$parsedSource["stats"]);
        }
        return new CommitDetail(/** @type {Partial<CommitDetail>} */($$parsedSource));
    }
}

/**
 * CommitFileInfo represents a file changed in a commit
 */
export class CommitFileInfo {
    /**
     * Creates a new CommitFileInfo instance.
     * @param {Partial<CommitFileInfo>} [$$source = {}] - The source object to create the CommitFileInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * For renames
             * @member
             * @type {string | undefined}
             */
            this["oldPath"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("additions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitFileInfo(/** @type {Partial<CommitFileInfo>} */($$parsedSource));
    }
}

/**
 * CommitInfo represents a single commit
 */
export class CommitInfo {
    /**
     * Creates a new CommitInfo instance.
     * @param {Partial<CommitInfo>} [$$source = {}] - The source object to create the CommitInfo.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativeDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo(/** @type {Partial<CommitInfo>} */($$parsedSource));
    }
}

/**
 * CommitStats contains overall statistics for a commit
 */
export class CommitStats {
    /**
     * Creates a new CommitStats instance.
     * @param {Partial<CommitStats>} [$$source = {}] - The source object to create the CommitStats.
     */
    constructor($$source = {}) {
        if (!("filesChanged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesChanged"] = 0;
        }
        if (!("additions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitStats(/** @type {Partial<CommitStats>} */($$parsedSource));
    }
}

/**
 * DiffHunk represents a single hunk in a diff
 */
export class DiffHunk {
    /**
     * Creates a new DiffHunk instance.
     * @param {Partial<DiffHunk>} [$$source = {}] - The source object to create the DiffHunk.
     */
    constructor($$source = {}) {
        if (!("oldStart" in $$source)) {
            /**
             * Starting line in old file
             * @member
             * @type {number}
             */
            this["oldStart"] = 0;
        }
        if (!("oldCount" in $$source)) {
            /**
             * Number of lines in old file
             * @member
             * @type {number}
             */
            this["oldCount"] = 0;
        }
        if (!("newStart" in $$source)) {
            /**
             * Starting line in new file
             * @member
             * @type {number}
             */
            this["newStart"] = 0;
        }
        if (!("newCount" in $$source)) {
            /**
             * Number of lines in new file
             * @member
             * @type {number}
             */
            this["newCount"] = 0;
        }
        if (!("header" in $$source)) {
            /**
             * The @@ header line
             * @member
             * @type {string}
             */
            this["header"] = "";
        }
        if (!("lines" in $$source)) {
            /**
             * Lines in this hunk
             * @member
             * @type {DiffLine[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffHunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffHunk}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField5_0($$parsedSource["lines"]);
        }
        return new DiffHunk(/** @type {Partial<DiffHunk>} */($$parsedSource));
    }
}

/**
 * DiffLine represents a single line in a diff
 */
export class DiffLine {
    /**
     * Creates a new DiffLine instance.
     * @param {Partial<DiffLine>} [$$source = {}] - The source object to create the DiffLine.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "context", "add", "delete"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * Line content (without +/- prefix)
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("oldLine" in $$source)) {
            /**
             * Line number in old file (0 if added)
             * @member
             * @type {number}
             */
            this["oldLine"] = 0;
        }
        if (!("newLine" in $$source)) {
            /**
             * Line number in new file (0 if deleted)
             * @member
             * @type {number}
             */
            this["newLine"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine(/** @type {Partial<DiffLine>} */($$parsedSource));
    }
}

/**
 * DirectoryContents contains the contents of a directory
 */
export class DirectoryContents {
    /**
     * Creates a new DirectoryContents instance.
     * @param {Partial<DirectoryContents>} [$$source = {}] - The source object to create the DirectoryContents.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {FileEntry[]}
             */
            this["entries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryContents instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryContents}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new DirectoryContents(/** @type {Partial<DirectoryContents>} */($$parsedSource));
    }
}

/**
 * FileDiff represents the diff for a single file
 */
export class FileDiff {
    /**
     * Creates a new FileDiff instance.
     * @param {Partial<FileDiff>} [$$source = {}] - The source object to create the FileDiff.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * For renames
             * @member
             * @type {string | undefined}
             */
            this["oldPath"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("binary" in $$source)) {
            /**
             * True if binary file
             * @member
             * @type {boolean}
             */
            this["binary"] = false;
        }
        if (!("hunks" in $$source)) {
            /**
             * @member
             * @type {DiffHunk[]}
             */
            this["hunks"] = [];
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileDiff}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hunks" in $$parsedSource) {
            $$parsedSource["hunks"] = $$createField4_0($$parsedSource["hunks"]);
        }
        return new FileDiff(/** @type {Partial<FileDiff>} */($$parsedSource));
    }
}

/**
 * FileEntry represents a file or directory in the file system
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDirectory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDirectory"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("extension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extension"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}

/**
 * FileStatus represents the status of a changed file
 */
export class FileStatus {
    /**
     * Creates a new FileStatus instance.
     * @param {Partial<FileStatus>} [$$source = {}] - The source object to create the FileStatus.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "added", "modified", "deleted", "renamed", "untracked"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStatus(/** @type {Partial<FileStatus>} */($$parsedSource));
    }
}

/**
 * GitVersion represents parsed git version
 */
export class GitVersion {
    /**
     * Creates a new GitVersion instance.
     * @param {Partial<GitVersion>} [$$source = {}] - The source object to create the GitVersion.
     */
    constructor($$source = {}) {
        if (!("Major" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Major"] = 0;
        }
        if (!("Minor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Minor"] = 0;
        }
        if (!("Patch" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Patch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitVersion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitVersion(/** @type {Partial<GitVersion>} */($$parsedSource));
    }
}

/**
 * OpenFileResult contains the result of opening a file
 */
export class OpenFileResult {
    /**
     * Creates a new OpenFileResult instance.
     * @param {Partial<OpenFileResult>} [$$source = {}] - The source object to create the OpenFileResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFileResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileResult(/** @type {Partial<OpenFileResult>} */($$parsedSource));
    }
}

/**
 * OpenFolderDialogResult contains the result of an open folder dialog
 */
export class OpenFolderDialogResult {
    /**
     * Creates a new OpenFolderDialogResult instance.
     * @param {Partial<OpenFolderDialogResult>} [$$source = {}] - The source object to create the OpenFolderDialogResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["selected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFolderDialogResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenFolderDialogResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFolderDialogResult(/** @type {Partial<OpenFolderDialogResult>} */($$parsedSource));
    }
}

/**
 * OperationResult represents the result of a git operation
 */
export class OperationResult {
    /**
     * Creates a new OperationResult instance.
     * @param {Partial<OperationResult>} [$$source = {}] - The source object to create the OperationResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OperationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationResult(/** @type {Partial<OperationResult>} */($$parsedSource));
    }
}

/**
 * RepoInfo contains basic information about a git repository
 */
export class RepoInfo {
    /**
     * Creates a new RepoInfo instance.
     * @param {Partial<RepoInfo>} [$$source = {}] - The source object to create the RepoInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoInfo(/** @type {Partial<RepoInfo>} */($$parsedSource));
    }
}

/**
 * RepoStatus contains the current state of a repository
 */
export class RepoStatus {
    /**
     * Creates a new RepoStatus instance.
     * @param {Partial<RepoStatus>} [$$source = {}] - The source object to create the RepoStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("ahead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }
        if (!("changedFiles" in $$source)) {
            /**
             * @member
             * @type {FileStatus[]}
             */
            this["changedFiles"] = [];
        }
        if (!("hasChanges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasChanges"] = false;
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changedFiles" in $$parsedSource) {
            $$parsedSource["changedFiles"] = $$createField3_0($$parsedSource["changedFiles"]);
        }
        return new RepoStatus(/** @type {Partial<RepoStatus>} */($$parsedSource));
    }
}

/**
 * TerminalResult contains the result of terminal operations
 */
export class TerminalResult {
    /**
     * Creates a new TerminalResult instance.
     * @param {Partial<TerminalResult>} [$$source = {}] - The source object to create the TerminalResult.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalResult(/** @type {Partial<TerminalResult>} */($$parsedSource));
    }
}

/**
 * UserProfile contains git user configuration
 */
export class UserProfile {
    /**
     * Creates a new UserProfile instance.
     * @param {Partial<UserProfile>} [$$source = {}] - The source object to create the UserProfile.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile(/** @type {Partial<UserProfile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BranchInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CommitFileInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CommitStats.createFrom;
const $$createType6 = DiffLine.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = FileEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = DiffHunk.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = FileStatus.createFrom;
const $$createType13 = $Create.Array($$createType12);
