// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProgressService handles git operations with progress reporting
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PullWithProgress performs git pull with progress updates
 * @param {string} repoPath
 * @param {string} operationID
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function PullWithProgress(repoPath, operationID) {
    return $Call.ByID(2224799466, repoPath, operationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PushWithProgress performs git push with progress updates
 * @param {string} repoPath
 * @param {string} operationID
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function PushWithProgress(repoPath, operationID) {
    return $Call.ByID(669744157, repoPath, operationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetApp sets the Wails application reference for event emission
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1421554813, app);
}

/**
 * SyncWithProgress performs git pull --rebase + push with progress updates
 * @param {string} repoPath
 * @param {string} operationID
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function SyncWithProgress(repoPath, operationID) {
    return $Call.ByID(3446382266, repoPath, operationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
