// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RepositorySettingsService manages repository-level configuration and background tasks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortCherryPick aborts an in-progress cherry-pick
 */
export function AbortCherryPick(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3075676282, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortMerge aborts an in-progress merge
 */
export function AbortMerge(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3726773886, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearCredentialCache clears cached credentials
 */
export function ClearCredentialCache(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3680370630, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteSettings removes settings for a repository
 */
export function DeleteSettings(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1556708562, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DiagnoseRepository runs diagnostics on the repository to identify issues
 */
export function DiagnoseRepository(repoPath: string): $CancellablePromise<$models.RecoveryDiagnostics> {
    return $Call.ByID(3698553048, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FixRemoteURL updates the remote URL (useful when remote has moved or credentials changed)
 */
export function FixRemoteURL(repoPath: string, remoteName: string, newURL: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3972947798, repoPath, remoteName, newURL).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAllGitConfigs returns all local git config values for the repository
 */
export function GetAllGitConfigs(repoPath: string): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(1942974272, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetDefaultSettings returns the default settings for a new repository
 */
export function GetDefaultSettings(repoPath: string): $CancellablePromise<$models.RepositorySettings> {
    return $Call.ByID(2254102032, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGitConfig returns a git config value for the repository
 */
export function GetGitConfig(repoPath: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(644831406, repoPath, key);
}

/**
 * GetReflog returns recent reflog entries for recovery purposes
 */
export function GetReflog(repoPath: string, limit: number): $CancellablePromise<$models.ReflogEntry[]> {
    return $Call.ByID(3399794441, repoPath, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRemotes returns all remotes for a repository
 */
export function GetRemotes(repoPath: string): $CancellablePromise<$models.GitRemoteInfo[]> {
    return $Call.ByID(819875727, repoPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSettings retrieves settings for a repository
 */
export function GetSettings(repoPath: string): $CancellablePromise<$models.RepositorySettings> {
    return $Call.ByID(1891688925, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTaskStatuses returns the current status of all background tasks
 */
export function GetTaskStatuses(): $CancellablePromise<{ [_: $models.BackgroundTaskType]: $models.BackgroundTaskStatus | null }> {
    return $Call.ByID(819743575).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * RecoverFromDetachedHead creates a new branch from detached HEAD or switches to an existing branch
 */
export function RecoverFromDetachedHead(repoPath: string, newBranchName: string, switchToExisting: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(732201568, repoPath, newBranchName, switchToExisting).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RecoverToReflogEntry recovers the repository to a specific reflog entry
 */
export function RecoverToReflogEntry(repoPath: string, hash: string, createBranch: boolean, branchName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1285510440, repoPath, hash, createBranch, branchName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RecreateRemote removes and re-adds a remote
 */
export function RecreateRemote(repoPath: string, remoteName: string, url: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(711869755, repoPath, remoteName, url).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RemoveStaleLocks removes stale lock files that may be blocking Git operations
 */
export function RemoveStaleLocks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3819853687, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RepairRepository attempts to repair common repository issues
 */
export function RepairRepository(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2586154113, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetHard performs a hard reset to a specific ref (use with caution)
 */
export function ResetHard(repoPath: string, ref: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(539485846, repoPath, ref, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetToDefaults resets all settings for a repository to defaults
 */
export function ResetToDefaults(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(154160752, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RestartBackgroundTasks restarts all background tasks for a repository
 */
export function RestartBackgroundTasks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(815219907, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RunTaskNow runs a background task immediately
 */
export function RunTaskNow(repoPath: string, taskType: $models.BackgroundTaskType): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1149003704, repoPath, taskType).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings saves settings for a repository
 */
export function SaveSettings(settings: $models.RepositorySettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2049636444, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the application reference (called after app initialization)
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4222581215, app);
}

/**
 * SetGitConfig sets a git config value for the repository
 */
export function SetGitConfig(repoPath: string, key: string, value: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4273837954, repoPath, key, value).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetUpstreamBranch sets the upstream tracking branch
 */
export function SetUpstreamBranch(repoPath: string, remoteBranch: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3179951841, repoPath, remoteBranch).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartBackgroundTasks starts background tasks for a repository
 */
export function StartBackgroundTasks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4255278974, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StashAndReset stashes current changes before resetting
 */
export function StashAndReset(repoPath: string, ref: string, stashMessage: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3577628009, repoPath, ref, stashMessage).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StopBackgroundTasks stops all background tasks for a repository
 */
export function StopBackgroundTasks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(348923034, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnsetGitConfig removes a git config value from the repository
 */
export function UnsetGitConfig(repoPath: string, key: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(148586465, repoPath, key).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateBackgroundTask updates the configuration for a specific background task
 */
export function UpdateBackgroundTask(repoPath: string, taskType: $models.BackgroundTaskType, config: $models.BackgroundTaskConfig): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(434843300, repoPath, taskType, config).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateFetchSettings updates fetch-related settings
 */
export function UpdateFetchSettings(repoPath: string, fetchSettings: $models.FetchSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(43262750, repoPath, fetchSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateLFSSettings updates LFS-related settings
 */
export function UpdateLFSSettings(repoPath: string, lfsSettings: $models.LFSSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3927914145, repoPath, lfsSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateMaintenanceSettings updates maintenance-related settings
 */
export function UpdateMaintenanceSettings(repoPath: string, maintenanceSettings: $models.MaintenanceSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4008011229, repoPath, maintenanceSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateProtectedBranches updates protected branch settings
 */
export function UpdateProtectedBranches(repoPath: string, protectedBranches: $models.ProtectedBranchSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(929215121, repoPath, protectedBranches).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.RecoveryDiagnostics.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.RepositorySettings.createFrom;
const $$createType4 = $models.ReflogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.GitRemoteInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.BackgroundTaskStatus.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
