// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RepositorySettingsService manages repository-level configuration and background tasks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortCherryPick aborts an in-progress cherry-pick
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function AbortCherryPick(repoPath) {
    return $Call.ByID(3075676282, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AbortMerge aborts an in-progress merge
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function AbortMerge(repoPath) {
    return $Call.ByID(3726773886, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearCredentialCache clears cached credentials
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ClearCredentialCache(repoPath) {
    return $Call.ByID(3680370630, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteSettings removes settings for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function DeleteSettings(repoPath) {
    return $Call.ByID(1556708562, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DiagnoseRepository runs diagnostics on the repository to identify issues
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.RecoveryDiagnostics>}
 */
export function DiagnoseRepository(repoPath) {
    return $Call.ByID(3698553048, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FixRemoteURL updates the remote URL (useful when remote has moved or credentials changed)
 * @param {string} repoPath
 * @param {string} remoteName
 * @param {string} newURL
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function FixRemoteURL(repoPath, remoteName, newURL) {
    return $Call.ByID(3972947798, repoPath, remoteName, newURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAllGitConfigs returns all local git config values for the repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAllGitConfigs(repoPath) {
    return $Call.ByID(1942974272, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetDefaultSettings returns the default settings for a new repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.RepositorySettings>}
 */
export function GetDefaultSettings(repoPath) {
    return $Call.ByID(2254102032, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetGitConfig returns a git config value for the repository
 * @param {string} repoPath
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetGitConfig(repoPath, key) {
    return $Call.ByID(644831406, repoPath, key);
}

/**
 * GetReflog returns recent reflog entries for recovery purposes
 * @param {string} repoPath
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ReflogEntry[]>}
 */
export function GetReflog(repoPath, limit) {
    return $Call.ByID(3399794441, repoPath, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetRemotes returns all remotes for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.GitRemoteInfo[]>}
 */
export function GetRemotes(repoPath) {
    return $Call.ByID(819875727, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetSettings retrieves settings for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.RepositorySettings>}
 */
export function GetSettings(repoPath) {
    return $Call.ByID(1891688925, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTaskStatuses returns the current status of all background tasks
 * @returns {$CancellablePromise<{ [_: $models.BackgroundTaskType]: $models.BackgroundTaskStatus | null }>}
 */
export function GetTaskStatuses() {
    return $Call.ByID(819743575).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * RecoverFromDetachedHead creates a new branch from detached HEAD or switches to an existing branch
 * @param {string} repoPath
 * @param {string} newBranchName
 * @param {string} switchToExisting
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RecoverFromDetachedHead(repoPath, newBranchName, switchToExisting) {
    return $Call.ByID(732201568, repoPath, newBranchName, switchToExisting).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RecoverToReflogEntry recovers the repository to a specific reflog entry
 * @param {string} repoPath
 * @param {string} hash
 * @param {boolean} createBranch
 * @param {string} branchName
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RecoverToReflogEntry(repoPath, hash, createBranch, branchName) {
    return $Call.ByID(1285510440, repoPath, hash, createBranch, branchName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RecreateRemote removes and re-adds a remote
 * @param {string} repoPath
 * @param {string} remoteName
 * @param {string} url
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RecreateRemote(repoPath, remoteName, url) {
    return $Call.ByID(711869755, repoPath, remoteName, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RemoveStaleLocks removes stale lock files that may be blocking Git operations
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RemoveStaleLocks(repoPath) {
    return $Call.ByID(3819853687, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RepairRepository attempts to repair common repository issues
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RepairRepository(repoPath) {
    return $Call.ByID(2586154113, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResetHard performs a hard reset to a specific ref (use with caution)
 * @param {string} repoPath
 * @param {string} ref
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ResetHard(repoPath, ref, confirm) {
    return $Call.ByID(539485846, repoPath, ref, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ResetToDefaults resets all settings for a repository to defaults
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function ResetToDefaults(repoPath) {
    return $Call.ByID(154160752, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RestartBackgroundTasks restarts all background tasks for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RestartBackgroundTasks(repoPath) {
    return $Call.ByID(815219907, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RunTaskNow runs a background task immediately
 * @param {string} repoPath
 * @param {$models.BackgroundTaskType} taskType
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function RunTaskNow(repoPath, taskType) {
    return $Call.ByID(1149003704, repoPath, taskType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveSettings saves settings for a repository
 * @param {$models.RepositorySettings} settings
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(2049636444, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetApp sets the application reference (called after app initialization)
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(4222581215, app);
}

/**
 * SetGitConfig sets a git config value for the repository
 * @param {string} repoPath
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function SetGitConfig(repoPath, key, value) {
    return $Call.ByID(4273837954, repoPath, key, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetUpstreamBranch sets the upstream tracking branch
 * @param {string} repoPath
 * @param {string} remoteBranch
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function SetUpstreamBranch(repoPath, remoteBranch) {
    return $Call.ByID(3179951841, repoPath, remoteBranch).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StartBackgroundTasks starts background tasks for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StartBackgroundTasks(repoPath) {
    return $Call.ByID(4255278974, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StashAndReset stashes current changes before resetting
 * @param {string} repoPath
 * @param {string} ref
 * @param {string} stashMessage
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StashAndReset(repoPath, ref, stashMessage) {
    return $Call.ByID(3577628009, repoPath, ref, stashMessage).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StopBackgroundTasks stops all background tasks for a repository
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function StopBackgroundTasks(repoPath) {
    return $Call.ByID(348923034, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UnsetGitConfig removes a git config value from the repository
 * @param {string} repoPath
 * @param {string} key
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UnsetGitConfig(repoPath, key) {
    return $Call.ByID(148586465, repoPath, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateBackgroundTask updates the configuration for a specific background task
 * @param {string} repoPath
 * @param {$models.BackgroundTaskType} taskType
 * @param {$models.BackgroundTaskConfig} config
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UpdateBackgroundTask(repoPath, taskType, config) {
    return $Call.ByID(434843300, repoPath, taskType, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateFetchSettings updates fetch-related settings
 * @param {string} repoPath
 * @param {$models.FetchSettings} fetchSettings
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UpdateFetchSettings(repoPath, fetchSettings) {
    return $Call.ByID(43262750, repoPath, fetchSettings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateLFSSettings updates LFS-related settings
 * @param {string} repoPath
 * @param {$models.LFSSettings} lfsSettings
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UpdateLFSSettings(repoPath, lfsSettings) {
    return $Call.ByID(3927914145, repoPath, lfsSettings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateMaintenanceSettings updates maintenance-related settings
 * @param {string} repoPath
 * @param {$models.MaintenanceSettings} maintenanceSettings
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UpdateMaintenanceSettings(repoPath, maintenanceSettings) {
    return $Call.ByID(4008011229, repoPath, maintenanceSettings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateProtectedBranches updates protected branch settings
 * @param {string} repoPath
 * @param {$models.ProtectedBranchSettings} protectedBranches
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function UpdateProtectedBranches(repoPath, protectedBranches) {
    return $Call.ByID(929215121, repoPath, protectedBranches).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.RecoveryDiagnostics.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.RepositorySettings.createFrom;
const $$createType4 = $models.ReflogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.GitRemoteInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.BackgroundTaskStatus.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
