// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService manages app and user settings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppSettings returns the current app settings
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetAppSettings() {
    return $Call.ByID(2022119110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetUserProfile returns the git user config (global or for a specific repo)
 * Uses concurrent goroutines to fetch name and email in parallel
 * @param {string} repoPath
 * @returns {$CancellablePromise<$models.UserProfile>}
 */
export function GetUserProfile(repoPath) {
    return $Call.ByID(2720888796, repoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveAppSettings saves the app settings
 * @param {$models.AppSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveAppSettings(settings) {
    return $Call.ByID(4145384893, settings);
}

/**
 * SetUserProfile sets the git user config
 * @param {string} repoPath
 * @param {$models.UserProfile} profile
 * @param {boolean} global
 * @returns {$CancellablePromise<$models.OperationResult>}
 */
export function SetUserProfile(repoPath, profile, global) {
    return $Call.ByID(3132053776, repoPath, profile, global).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $models.UserProfile.createFrom;
const $$createType2 = $models.OperationResult.createFrom;
