// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages PTY-based terminal sessions
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseAllSessions terminates all terminal sessions
 * @returns {$CancellablePromise<void>}
 */
export function CloseAllSessions() {
    return $Call.ByID(1431312923);
}

/**
 * CloseSession terminates a terminal session
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.TerminalResult>}
 */
export function CloseSession(sessionID) {
    return $Call.ByID(2632171917, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateSession creates a new terminal session
 * @param {string} workingDir
 * @returns {$CancellablePromise<$models.TerminalResult>}
 */
export function CreateSession(workingDir) {
    return $Call.ByID(322758575, workingDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDefaultDirectory returns the default working directory
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultDirectory() {
    return $Call.ByID(2357861123);
}

/**
 * GetDefaultShell returns the default shell for the current OS
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultShell() {
    return $Call.ByID(508604754);
}

/**
 * ResizeTerminal resizes the PTY
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<$models.TerminalResult>}
 */
export function ResizeTerminal(sessionID, cols, rows) {
    return $Call.ByID(3648900693, sessionID, cols, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetApp sets the Wails application reference for event emission
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1356505526, app);
}

/**
 * WriteInput sends input to the terminal session
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<$models.TerminalResult>}
 */
export function WriteInput(sessionID, data) {
    return $Call.ByID(4128655824, sessionID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TerminalResult.createFrom;
