// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppUpdateService is the frontend-facing coordinator for Wails' built-in
 * updater. Update operations are available only in production Windows/amd64
 * builds and are serialized so a manual check cannot race a background check.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckForUpdates opens Wails' built-in updater window and runs an update flow.
 * Unsupported and development builds intentionally treat the call as a no-op.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(1969794563);
}

/**
 * GetCurrentVersion returns the normalized version configured at build time.
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(4003058871);
}
