// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService provides secure session persistence via the OS keychain.
 * The frontend calls SaveSession after successful login, LoadSession on app
 * startup to rehydrate, and ClearSession on logout.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ClearSession removes the stored session from the OS keychain.
 * It is a no-op (no error) if no session exists.
 */
export function ClearSession(): $CancellablePromise<void> {
    return $Call.ByID(4149955217);
}

/**
 * LoadSession retrieves the stored Supabase session JSON from the OS keychain.
 * Returns an empty string (no error) if no session has been stored yet, so the
 * frontend can treat empty-string as "not authenticated".
 */
export function LoadSession(): $CancellablePromise<string> {
    return $Call.ByID(1486670922);
}

/**
 * SaveSession stores the serialised Supabase session JSON in the OS keychain.
 * It overwrites any previously stored session.
 */
export function SaveSession(sessionJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3679177501, sessionJSON);
}
