// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConflictQueueService owns the conflicted file queue for one repository.
 * It never resolves conflicts; it only reports which files still need a
 * decision and what can be done with each of them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachToBus subscribes the queue to repository mutation events so any
 * operation that can create or clear conflicts refreshes the queue.
 */
export function AttachToBus(bus: $models.RepoEventBus | null): $CancellablePromise<void> {
    return $Call.ByID(3218966251, bus);
}

/**
 * ClearRepository unbinds the queue and emits an empty snapshot.
 */
export function ClearRepository(): $CancellablePromise<$models.ConflictQueueSnapshot> {
    return $Call.ByID(332920136).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetachFromBus removes the bus subscription, if any.
 */
export function DetachFromBus(): $CancellablePromise<void> {
    return $Call.ByID(690322058);
}

/**
 * GetConflictQueue returns the current snapshot without rescanning.
 */
export function GetConflictQueue(): $CancellablePromise<$models.ConflictQueueSnapshot> {
    return $Call.ByID(2792245334).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Refresh forces an immediate rescan, coalesced with any scan already running.
 */
export function Refresh(): $CancellablePromise<$models.ConflictQueueSnapshot> {
    return $Call.ByID(4276864702).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the Wails application reference for event emission.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(11458008, app);
}

/**
 * SetRepository binds the queue to a repository, clearing any prior state, and
 * scans once so the caller receives an immediately usable snapshot.
 */
export function SetRepository(repoPath: string): $CancellablePromise<$models.ConflictQueueSnapshot> {
    return $Call.ByID(2906642793, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConflictQueueSnapshot.createFrom;
