// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DebugService is the Wails-exposed service for the debug logging system.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs removes all entries from the ring buffer.
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2613125385);
}

/**
 * ExportLogs writes all current entries to a JSON file on disk and returns the path.
 * Returns an empty string if export fails.
 */
export function ExportLogs(): $CancellablePromise<string> {
    return $Call.ByID(248138472);
}

/**
 * GetLogByID retrieves a single log entry by its unique ID.
 * Returns nil if not found.
 */
export function GetLogByID(id: number): $CancellablePromise<$models.LogEntry | null> {
    return $Call.ByID(3486691767, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLogs returns log entries matching the given filter.
 */
export function GetLogs(filter: $models.LogFilter): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(2123370372, filter).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetStats returns a summary of the logger state (entry counts, buffer usage, etc.).
 */
export function GetStats(): $CancellablePromise<$models.DebugStats> {
    return $Call.ByID(2838011106).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsEnabled returns whether debug logging is currently active.
 */
export function IsEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3290320886);
}

/**
 * SetEnabled toggles debug logging on or off at runtime.
 */
export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2814417696, enabled);
}

// Private type creation functions
const $$createType0 = $models.LogEntry.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.DebugStats.createFrom;
