// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileWatcherService watches directories for file changes and emits events
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetWatchedPath returns the currently watched path
 */
export function GetWatchedPath(): $CancellablePromise<string> {
    return $Call.ByID(3376255377);
}

/**
 * SetApp sets the Wails application reference for event emission
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(504384071, app);
}

/**
 * StopWatching stops watching the current directory
 */
export function StopWatching(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2716782321).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WatchDirectory starts watching a directory for changes
 * Returns an error if the directory cannot be watched
 */
export function WatchDirectory(path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3149356166, path).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
