// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileSystemService provides file system operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyToClipboard copies the given text to the system clipboard
 */
export function CopyToClipboard(text: string): $CancellablePromise<$models.OpenFileResult> {
    return $Call.ByID(4270447151, text).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetParentDirectory returns the parent directory of the given path
 */
export function GetParentDirectory(path: string): $CancellablePromise<string> {
    return $Call.ByID(2630067680, path);
}

/**
 * ListDirectory lists the contents of a directory (excludes hidden files by default)
 */
export function ListDirectory(path: string): $CancellablePromise<$models.DirectoryContents> {
    return $Call.ByID(3353852338, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDirectoryWithOptions lists the contents of a directory with options
 * includeHidden: if true, includes hidden files (starting with .)
 */
export function ListDirectoryWithOptions(path: string, includeHidden: boolean): $CancellablePromise<$models.DirectoryContents> {
    return $Call.ByID(1676200912, path, includeHidden).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenFile opens a file with the default application
 */
export function OpenFile(path: string): $CancellablePromise<$models.OpenFileResult> {
    return $Call.ByID(530707657, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenInTerminal opens a terminal at the specified path
 */
export function OpenInTerminal(path: string): $CancellablePromise<$models.OpenFileResult> {
    return $Call.ByID(604884284, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReadTextFile reads the content of a text file
 */
export function ReadTextFile(path: string): $CancellablePromise<$models.ReadTextFileResult> {
    return $Call.ByID(3246798046, path).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RevealInFinder opens the containing folder in the system file manager and selects the file
 */
export function RevealInFinder(path: string): $CancellablePromise<$models.OpenFileResult> {
    return $Call.ByID(3332293609, path).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OpenFileResult.createFrom;
const $$createType1 = $models.DirectoryContents.createFrom;
const $$createType2 = $models.ReadTextFileResult.createFrom;
