// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitHubService provides GitHub CLI (gh) operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AuthLogin initiates the GitHub authentication flow using device code.
 * This runs the gh auth login command and waits for completion.
 * The flow shows a code that the user must enter in their browser.
 */
export function AuthLogin(): $CancellablePromise<$models.GitHubAuthResult> {
    return $Call.ByID(3633986302).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AuthLoginCancel cancels an in-progress device flow authentication
 */
export function AuthLoginCancel(): $CancellablePromise<$models.GitHubAuthResult> {
    return $Call.ByID(979810388).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AuthLoginComplete checks if the device flow authentication has completed.
 * This should be called after AuthLoginStart and after the user has entered the code.
 * It polls the auth status to detect successful authentication.
 */
export function AuthLoginComplete(): $CancellablePromise<$models.GitHubAuthResult> {
    return $Call.ByID(1398634085).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AuthLoginStart initiates the device code authentication flow.
 * Returns the user code and verification URL for the user to complete auth in browser.
 * After calling this, call AuthLoginComplete to wait for the auth to finish.
 * The gh CLI process will continue running in the background until the user completes auth.
 */
export function AuthLoginStart(): $CancellablePromise<$models.GitHubDeviceFlowResult> {
    return $Call.ByID(2121897454).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AuthLogout logs out of GitHub CLI
 */
export function AuthLogout(): $CancellablePromise<$models.GitHubAuthResult> {
    return $Call.ByID(2541881663).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AuthStatus checks the current authentication status
 */
export function AuthStatus(): $CancellablePromise<$models.GitHubAuthStatus> {
    return $Call.ByID(3725782427).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CheckRepoNameExists checks whether a repository with the given name already
 * exists under the specified owner (user or org). Uses `gh repo view` which
 * returns exit code 0 when the repo exists and a non-zero code when it does not.
 * owner: GitHub username or organization login
 * name: repository name to check
 */
export function CheckRepoNameExists(owner: string, name: string): $CancellablePromise<$models.RepoNameCheckResult> {
    return $Call.ByID(3422910298, owner, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGHVersion returns the installed GitHub CLI version
 */
export function GetGHVersion(): $CancellablePromise<string> {
    return $Call.ByID(2628927162);
}

/**
 * IsGHInstalled checks if the GitHub CLI (gh) is installed and available
 */
export function IsGHInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(2985805654);
}

/**
 * ListUserOrganizations returns the authenticated user's username and their organizations
 * This is used for the "publish to GitHub" form to allow users to choose the repo owner
 */
export function ListUserOrganizations(): $CancellablePromise<$models.GitHubOrganizationsResult> {
    return $Call.ByID(2146096128).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RepoClone clones a GitHub repository to the specified directory
 * repo: repository in "owner/repo" format or full URL
 * destPath: local directory to clone into (will be created)
 * shallow: when true, clone only the latest commit history (depth=1)
 */
export function RepoClone(repo: string, destPath: string, shallow: boolean): $CancellablePromise<$models.GitHubCloneResult> {
    return $Call.ByID(3713232932, repo, destPath, shallow).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RepoCreate creates a new repository on GitHub
 */
export function RepoCreate(options: $models.GitHubRepoCreateOptions): $CancellablePromise<$models.GitHubRepoCreateResult> {
    return $Call.ByID(1420268655, options).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RepoCreateFromLocal creates a new GitHub repository from an existing local repository
 * localPath: path to the local git repository
 * name: name for the new GitHub repository (optional, defaults to folder name)
 * description: repository description
 * private: whether the repository should be private
 * owner: the owner for the repository (username or organization login). If empty, defaults to authenticated user.
 */
export function RepoCreateFromLocal(localPath: string, name: string, description: string, $private: boolean, owner: string): $CancellablePromise<$models.GitHubRepoCreateResult> {
    return $Call.ByID(1048591282, localPath, name, description, $private, owner).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RepoList lists repositories for the authenticated user
 * limit: maximum number of repos to return (default 30, max 100)
 * visibility: "public", "private", or empty for all
 */
export function RepoList(limit: number, visibility: string): $CancellablePromise<$models.GitHubRepoListResult> {
    return $Call.ByID(106928271, limit, visibility).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * RepoListForOrg lists repositories for a specific organization
 */
export function RepoListForOrg(org: string, limit: number): $CancellablePromise<$models.GitHubRepoListResult> {
    return $Call.ByID(1651014432, org, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GitHubAuthResult.createFrom;
const $$createType1 = $models.GitHubDeviceFlowResult.createFrom;
const $$createType2 = $models.GitHubAuthStatus.createFrom;
const $$createType3 = $models.RepoNameCheckResult.createFrom;
const $$createType4 = $models.GitHubOrganizationsResult.createFrom;
const $$createType5 = $models.GitHubCloneResult.createFrom;
const $$createType6 = $models.GitHubRepoCreateResult.createFrom;
const $$createType7 = $models.GitHubRepoListResult.createFrom;
