// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService provides git operations via CLI
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortAM aborts the current AM (patch application) operation.
 * Runs: git am --abort
 */
export function AbortAM(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3254738718, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortBisect aborts the current bisect session.
 * Runs: git bisect reset
 */
export function AbortBisect(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(960387302, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortCherryPick aborts the current cherry-pick operation.
 * Runs: git cherry-pick --abort
 */
export function AbortCherryPick(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3790816276, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortCurrentOperation aborts whatever stuck operation is currently in progress.
 * This is a convenience method that detects the state and calls the appropriate abort.
 */
export function AbortCurrentOperation(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4067841994, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortMerge aborts the current merge operation.
 * Returns the repository to the state before the merge started.
 * Handles both regular merges (MERGE_HEAD) and squash merges (SQUASH_MSG).
 */
export function AbortMerge(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3116495328, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortRevert aborts the current revert operation.
 * Runs: git revert --abort
 */
export function AbortRevert(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(409655226, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Add stages a specific file or directory for commit.
 * Equivalent to: git add <path>
 */
export function Add(repoPath: string, path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3982870129, repoPath, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddAll stages all changes in the repository.
 * Equivalent to: git add .
 */
export function AddAll(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2458942728, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddFiles stages multiple files for commit.
 * Equivalent to: git add -- <paths...>
 */
export function AddFiles(repoPath: string, paths: string[]): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3432617964, repoPath, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Branches returns all branches in the repository
 * Uses concurrent goroutines to fetch current, local, and remote branches in parallel
 */
export function Branches(repoPath: string): $CancellablePromise<$models.BranchList> {
    return $Call.ByID(2996696402, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckBranchConflicts checks for potential merge conflicts when merging the source branch
 * INTO the target branch without actually performing the merge.
 * This uses `git merge-tree --write-tree` which performs a merge simulation.
 * 
 * Default behavior (when sourceBranch is empty):
 * - Checks conflicts for merging current branch INTO targetBranch
 * 
 * Parameterized behavior (when both are provided):
 * - Checks conflicts for merging sourceBranch INTO targetBranch
 * 
 * The method:
 * 1. Auto-detects target branch (parent) if not provided
 * 2. Fetches the target branch from origin to ensure we have the latest
 * 3. Runs git merge-tree to detect conflicts (simulating merge into target)
 * 4. Returns the list of conflicted files if any
 * 
 * Parameters:
 *   - repoPath: Path to the git repository
 *   - targetBranch: Name of the target branch to merge INTO (e.g., "main", "master").
 *     If empty, the parent branch will be auto-detected.
 *   - sourceBranch: Optional. Name of the source branch to merge FROM.
 *     If empty, defaults to the current branch.
 * 
 * Returns:
 *   - BranchConflictCheckResult with conflict information
 */
export function CheckBranchConflicts(repoPath: string, targetBranch: string, ...sourceBranch: string[]): $CancellablePromise<$models.BranchConflictCheckResult> {
    return $Call.ByID(7778489, repoPath, targetBranch, sourceBranch).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CheckForStaleLocks returns a list of any lock files found in .git directory.
 */
export function CheckForStaleLocks(repoPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(2124716010, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CheckLockFile checks if a .git/index.lock file exists in the repository.
 * This lock file is created by Git during operations and can be left behind if
 * a process crashes or is interrupted.
 */
export function CheckLockFile(repoPath: string): $CancellablePromise<$models.LockFileInfo> {
    return $Call.ByID(2390930803, repoPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Checkout switches to a branch or commit without safety checks.
 * For safer operations with checks, use CheckoutBranch.
 * Equivalent to: git checkout <ref>
 */
export function Checkout(repoPath: string, ref: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(254446414, repoPath, ref).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckoutBranch switches to an existing branch.
 * Fails if there are uncommitted changes to prevent accidental loss.
 */
export function CheckoutBranch(repoPath: string, branchName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(272806078, repoPath, branchName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckoutNewBranch creates a new branch and switches to it without safety checks.
 * For safer operations with checks, use CreateBranchAndCheckout.
 * Equivalent to: git checkout -b <branch>
 */
export function CheckoutNewBranch(repoPath: string, branchName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2751510696, repoPath, branchName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Clean removes untracked files from the working directory.
 * Does NOT remove ignored files by default.
 * Equivalent to: git clean -fd
 */
export function Clean(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1402270439, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CleanDryRun shows what files would be removed by Clean without actually removing them.
 * Equivalent to: git clean -fdn
 */
export function CleanDryRun(repoPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(3917172525, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Commit creates a commit with staged changes.
 * Does NOT auto-stage anything - use Add/AddAll first.
 * Equivalent to: git commit -m <message>
 */
export function Commit(repoPath: string, message: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1270424519, repoPath, message).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CommitAll stages all changes and commits with the given message.
 * This is a composite operation that combines AddAll + Commit.
 * For finer control, use AddAll() and Commit() separately.
 */
export function CommitAll(repoPath: string, message: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2762480610, repoPath, message).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CompleteMerge completes the merge by committing after all conflicts are resolved.
 * Supports both regular merges (MERGE_HEAD) and squash merges (SQUASH_MSG).
 */
export function CompleteMerge(repoPath: string, message: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(370211995, repoPath, message).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CompleteSquashMerge commits a squash merge.
 * Unlike CompleteMerge, this doesn't require being in a merge state (no MERGE_HEAD).
 * It simply commits the staged changes from the squash merge.
 * 
 * Prefer using CompleteMerge which auto-detects the merge type and delegates here
 * for squash merges. This method is kept public for backward compatibility.
 */
export function CompleteSquashMerge(repoPath: string, message: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3207029892, repoPath, message).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ContinueCherryPick continues the cherry-pick after conflicts are resolved.
 * Runs: git cherry-pick --continue
 */
export function ContinueCherryPick(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1951010683, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ContinueRevert continues the revert after conflicts are resolved.
 * Runs: git revert --continue
 */
export function ContinueRevert(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2514630157, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateBranchAndCheckout creates a new branch and switches to it.
 * Fails if there are uncommitted changes or if the branch name is invalid.
 */
export function CreateBranchAndCheckout(repoPath: string, branchName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2251096979, repoPath, branchName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateBranchFromDetached creates a new branch from the current detached HEAD position.
 * This saves the user's work by attaching it to a named branch.
 */
export function CreateBranchFromDetached(repoPath: string, branchName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2050814244, repoPath, branchName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetectRepo checks if the given path is a git repository
 */
export function DetectRepo(path: string): $CancellablePromise<$models.RepoInfo> {
    return $Call.ByID(2256312149, path).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DiffCommitFileRaw returns the raw unified diff text for a specific file in a commit
 */
export function DiffCommitFileRaw(repoPath: string, hash: string, filePath: string): $CancellablePromise<$models.RawDiffResult> {
    return $Call.ByID(3273729992, repoPath, hash, filePath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * DiffWorkingRaw returns the raw unified diff text of a file in the working tree vs HEAD
 * This is designed to be consumed by react-diff-view's parseDiff function
 */
export function DiffWorkingRaw(repoPath: string, filePath: string): $CancellablePromise<$models.RawDiffResult> {
    return $Call.ByID(97595618, repoPath, filePath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * DiscardAll discards all uncommitted changes in the working directory.
 * This includes modified files, staged changes, and untracked files.
 * Requires confirm=true as a safety measure for destructive operations.
 * This is a composite operation that combines UnstageAll() + RestoreAll() + Clean().
 * For finer control, use those methods separately.
 */
export function DiscardAll(repoPath: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4274134007, repoPath, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DiscardFile discards changes to a specific file.
 * For untracked files, the file is deleted. For tracked files, changes are reverted to HEAD.
 * Requires confirm=true as a safety measure for destructive operations.
 * This is a composite operation that combines Unstage() + Restore() or file deletion.
 * For finer control, use those methods separately.
 */
export function DiscardFile(repoPath: string, filePath: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1158166522, repoPath, filePath, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Fetch downloads objects and refs from the remote without merging.
 * Equivalent to: git fetch [remote] [branch]
 */
export function Fetch(repoPath: string, remote: string, branch: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(94614478, repoPath, remote, branch).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FetchAll fetches from all remotes.
 * Equivalent to: git fetch --all
 */
export function FetchAll(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(919354909, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetBisectState returns information about the current bisect session.
 */
export function GetBisectState(repoPath: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3805468497, repoPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetCommitGraph returns commits with parent references and branch/tag info for graph visualization
 */
export function GetCommitGraph(repoPath: string, limit: number): $CancellablePromise<$models.CommitGraphResult> {
    return $Call.ByID(3628939361, repoPath, limit).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetConflictSidesInfo returns commit information for both sides of a conflict.
 * This is useful for displaying in the conflict resolution UI.
 * Parameters:
 *   - repoPath: Path to the git repository
 *   - parentBranch: The branch being merged from (theirs)
 */
export function GetConflictSidesInfo(repoPath: string, parentBranch: string): $CancellablePromise<$models.ConflictSidesInfo> {
    return $Call.ByID(428205696, repoPath, parentBranch).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetConflictedFiles returns a list of files with merge conflicts.
 */
export function GetConflictedFiles(repoPath: string): $CancellablePromise<$models.ConflictedFile[]> {
    return $Call.ByID(484033912, repoPath).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetCurrentBranch returns the name of the current branch.
 * Returns empty string if in detached HEAD state.
 */
export function GetCurrentBranch(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(935044367, repoPath);
}

/**
 * GetGitVersion returns the installed git version.
 * Used to determine feature compatibility (e.g., git restore requires 2.23+).
 */
export function GetGitVersion(): $CancellablePromise<$models.GitVersion | null> {
    return $Call.ByID(2885829042).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetMergeState detects if the repository is in any stuck/interrupted state.
 * Checks for: merge, rebase, cherry-pick, revert, bisect, AM, detached HEAD, and stale locks.
 */
export function GetMergeState(repoPath: string): $CancellablePromise<$models.MergeState> {
    return $Call.ByID(844598379, repoPath).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetParentBranch attempts to detect the parent branch of the current branch.
 * It uses multiple heuristics in order of reliability:
 * 1. Upstream tracking branch (git config branch.<name>.merge)
 * 2. Merge-base with common default branches (main, master, develop)
 * 3. Falls back to "main" or "master" if they exist
 * 
 * Returns the detected parent branch name and the source of detection.
 */
export function GetParentBranch(repoPath: string): $CancellablePromise<$models.ParentBranchResult> {
    return $Call.ByID(1659162422, repoPath).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetProtectedBranches returns the list of protected branch names.
 * Reads from .control-zebra/config.json in the repo, falls back to defaults.
 */
export function GetProtectedBranches(repoPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(975741992, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRecentCommits returns recent commits from the repository
 */
export function GetRecentCommits(repoPath: string, limit: number): $CancellablePromise<$models.CommitInfo[]> {
    return $Call.ByID(4130048517, repoPath, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetRemoteURL returns the URL of the origin remote, or empty string if not set
 */
export function GetRemoteURL(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(3646388877, repoPath);
}

/**
 * HasChanges returns true if the repository has uncommitted changes.
 */
export function HasChanges(repoPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2297511263, repoPath);
}

/**
 * HasStagedChanges returns true if there are staged (but uncommitted) changes.
 */
export function HasStagedChanges(repoPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2014791321, repoPath);
}

/**
 * InitRepo initializes a new Git repository at the given path.
 * Creates the directory if it doesn't exist.
 * Returns an error if the path is already a Git repository.
 */
export function InitRepo(path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(930497596, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * InitRepoWithLFS initializes a new Git repository with LFS enabled.
 * Creates the directory if it doesn't exist, runs git init, then git lfs install.
 */
export function InitRepoWithLFS(path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2769753051, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsDetachedHead checks if the repository is in a detached HEAD state.
 */
export function IsDetachedHead(repoPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2286894754, repoPath);
}

/**
 * IsProtectedBranch checks if the given branch name is in the protected list.
 * Uses the configured list from settings, falling back to defaults.
 */
export function IsProtectedBranch(repoPath: string, branchName: string): $CancellablePromise<boolean> {
    return $Call.ByID(1223160836, repoPath, branchName);
}

/**
 * MarkResolved marks a file as resolved after manual editing.
 * Runs: git add <path>
 */
export function MarkResolved(repoPath: string, filePath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1152182123, repoPath, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * MoveFile renames/moves a file and stages the change.
 * Equivalent to: git mv <source> <destination>
 */
export function MoveFile(repoPath: string, source: string, destination: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3955727001, repoPath, source, destination).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Pull fetches and merges changes from the remote
 */
export function Pull(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1098588353, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Push pushes local commits to the remote
 */
export function Push(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1132982234, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RemoveAllStaleLocks removes all stale lock files from the .git directory.
 * This is a convenience method that removes all known lock files at once.
 */
export function RemoveAllStaleLocks(repoPath: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2318621430, repoPath, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RemoveFile removes a file from the working tree and stages the removal.
 * Equivalent to: git rm <path>
 */
export function RemoveFile(repoPath: string, path: string, cached: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1703072200, repoPath, path, cached).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RemoveLockFile removes the .git/index.lock file from the repository.
 * This is useful for recovering from a stale lock file left behind by a crashed
 * Git process. Returns an OperationResult indicating success or failure.
 * 
 * CAUTION: Only call this when you are certain no other Git operation is in progress.
 * Removing a lock file while another Git process is running can cause corruption.
 */
export function RemoveLockFile(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4110976079, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RemoveStaleLock removes a specific lock file from the .git directory.
 * This is a potentially dangerous operation - requires confirmation.
 */
export function RemoveStaleLock(repoPath: string, lockFile: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(764376340, repoPath, lockFile, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetHard resets HEAD, index, and working tree to a specific commit.
 * WARNING: This is destructive - all uncommitted changes are lost.
 * Equivalent to: git reset --hard <ref>
 */
export function ResetHard(repoPath: string, ref: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(58112180, repoPath, ref).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetHardHead resets the working directory to HEAD, discarding all uncommitted changes.
 * This is the "Rewind" feature - returns to the last committed state.
 * Requires confirm=true as a safety measure for destructive operations.
 * This is a composite operation that combines ResetHard("HEAD") + Clean().
 * For finer control, use ResetHard() and Clean() separately.
 */
export function ResetHardHead(repoPath: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(348508294, repoPath, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetMixed resets HEAD and index to a specific commit, keeping working tree changes.
 * This is the default git reset behavior.
 * Equivalent to: git reset <ref>
 */
export function ResetMixed(repoPath: string, ref: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(509754688, repoPath, ref).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetSoft resets HEAD to a specific commit but keeps all changes staged.
 * Equivalent to: git reset --soft <ref>
 */
export function ResetSoft(repoPath: string, ref: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2939470669, repoPath, ref).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetSoftHead undoes the last n commits, keeping changes staged.
 * This is the "Undo Last Save" feature - changes remain in the working directory.
 * Requires confirm=true as a safety measure for destructive operations.
 * This is a wrapper around ResetSoft() with validation.
 */
export function ResetSoftHead(repoPath: string, n: number, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2645939291, repoPath, n, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveConflictKeepBoth resolves a conflict by keeping both versions.
 * The incoming (theirs) version keeps the original filename.
 * The local (mine) version is saved with a timestamp suffix to avoid collisions.
 * For example: file.txt becomes incoming version, file_COPY_20260115_143052.txt is local version.
 */
export function ResolveConflictKeepBoth(repoPath: string, filePath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1635013574, repoPath, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveConflictKeepOurs resolves a conflict by keeping our version.
 * Runs: git checkout --ours <path> && git add <path>
 */
export function ResolveConflictKeepOurs(repoPath: string, filePath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1586716466, repoPath, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveConflictKeepTheirs resolves a conflict by keeping their version.
 * Runs: git checkout --theirs <path> && git add <path>
 */
export function ResolveConflictKeepTheirs(repoPath: string, filePath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3794143328, repoPath, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Restore reverts a file to its HEAD state, discarding working tree changes.
 * Does NOT affect staged changes - use Unstage first if needed.
 * Equivalent to: git restore <path> (Git 2.23+) or git checkout -- <path>
 */
export function Restore(repoPath: string, path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1606765776, repoPath, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RestoreAll reverts all tracked files to HEAD state.
 * Does NOT remove untracked files - use Clean for that.
 * Equivalent to: git restore . (Git 2.23+) or git checkout -- .
 */
export function RestoreAll(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2271909699, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RevertCommit creates a new commit that undoes the changes from a specified commit.
 * Unlike reset, this preserves history by creating a new "anti-commit".
 * Requires a clean working tree (no uncommitted changes).
 * If the revert causes conflicts, the repo will be in a revert state.
 * Use AbortRevert() to cancel or ContinueRevert() after resolving conflicts.
 * Runs: git revert --no-edit <commitHash>
 */
export function RevertCommit(repoPath: string, commitHash: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(779702585, repoPath, commitHash).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RevertCommitWithMessage creates a new commit that undoes the changes from a specified commit
 * with a custom commit message.
 * Requires a clean working tree (no uncommitted changes).
 * Runs: git revert -m <message> <commitHash> (via stdin for message)
 */
export function RevertCommitWithMessage(repoPath: string, commitHash: string, message: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2725214252, repoPath, commitHash, message).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetProtectedBranches updates the list of protected branches for the repo.
 * Stores in .control-zebra/config.json in the repository.
 */
export function SetProtectedBranches(repoPath: string, branches: string[]): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2709150644, repoPath, branches).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ShowCommit returns detailed information about a specific commit
 * Uses concurrent goroutines to fetch metadata, numstat, and name-status in parallel
 */
export function ShowCommit(repoPath: string, hash: string): $CancellablePromise<$models.CommitDetail> {
    return $Call.ByID(137660310, repoPath, hash).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * SkipAMPatch skips the current patch in an AM sequence.
 * Runs: git am --skip
 */
export function SkipAMPatch(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2068617355, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SkipCherryPickCommit skips the current commit in a cherry-pick sequence.
 * Runs: git cherry-pick --skip
 */
export function SkipCherryPickCommit(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2445030508, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SkipRevertCommit skips the current commit in a revert sequence.
 * Runs: git revert --skip
 */
export function SkipRevertCommit(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2381417206, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartMerge begins an actual merge.
 * Uses --no-commit to allow the user to resolve conflicts before committing.
 * This is called after CheckBranchConflicts confirms there will be conflicts.
 * 
 * Default behavior (when sourceBranch is empty):
 * - Merges the current branch INTO the targetBranch
 * - First checks out targetBranch, then merges the original current branch
 * 
 * Parameterized behavior (when both are provided):
 * - Checks out targetBranch
 * - Merges sourceBranch into it
 * 
 * Parameters:
 *   - repoPath: Path to the git repository
 *   - targetBranch: The branch to merge INTO (e.g., "main") - required
 *   - sourceBranch: The branch to merge FROM (optional, defaults to current branch)
 */
export function StartMerge(repoPath: string, targetBranch: string, ...sourceBranch: string[]): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3602986874, repoPath, targetBranch, sourceBranch).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartMergeWithOptions begins a merge with configurable options.
 * Supports squash merge mode which combines all commits into a single commit.
 * 
 * Parameters:
 *   - repoPath: Path to the git repository
 *   - targetBranch: The branch to merge INTO (e.g., "main") - required
 *   - sourceBranch: The branch to merge FROM - required
 *   - options: MergeOptions with squash flag
 * 
 * When squash is true:
 * - Uses `git merge --squash` instead of regular merge
 * - Does NOT create a merge commit with two parents
 * - All changes appear as a single commit authored by the user
 * - Results in cleaner, linear history
 */
export function StartMergeWithOptions(repoPath: string, targetBranch: string, sourceBranch: string, options: $models.MergeOptions): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2111811496, repoPath, targetBranch, sourceBranch, options).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StashAndSwitchBranch performs a safe branch switch by stashing changes first.
 * Flow: stash push → checkout (or checkout -b if createNew) → stash pop
 * If the stash pop fails due to conflicts, the stash is preserved.
 */
export function StashAndSwitchBranch(repoPath: string, targetBranch: string, createNew: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3570517492, repoPath, targetBranch, createNew).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StashDrop removes a specific stash entry by index.
 * Requires confirm=true as a safety measure.
 */
export function StashDrop(repoPath: string, index: number, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3600053038, repoPath, index, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StashList returns all stash entries.
 */
export function StashList(repoPath: string): $CancellablePromise<$models.StashEntry[]> {
    return $Call.ByID(2553569151, repoPath).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * StashPop applies the most recent stash and removes it from the stash list.
 */
export function StashPop(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(342633834, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StashPush creates a new stash with an optional message.
 * Stashes all tracked changes (staged and unstaged).
 */
export function StashPush(repoPath: string, message: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3552291683, repoPath, message).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Status returns the current status of the repository
 * Uses concurrent goroutines to fetch branch, ahead/behind, and status in parallel
 */
export function Status(repoPath: string): $CancellablePromise<$models.RepoStatus> {
    return $Call.ByID(2928711956, repoPath).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * SupportsRestore returns true if git version supports 'git restore' (2.23+)
 */
export function SupportsRestore(): $CancellablePromise<boolean> {
    return $Call.ByID(3341958236);
}

/**
 * Sync performs a git pull (merge) followed by git push
 */
export function Sync(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2968559073, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Unstage removes a file from the staging area without discarding changes.
 * Equivalent to: git restore --staged <path> (Git 2.23+) or git reset HEAD <path>
 */
export function Unstage(repoPath: string, path: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1167094881, repoPath, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnstageAll removes all files from the staging area.
 * Equivalent to: git restore --staged . (Git 2.23+) or git reset HEAD
 */
export function UnstageAll(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2725489176, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.BranchList.createFrom;
const $$createType2 = $models.BranchConflictCheckResult.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.LockFileInfo.createFrom;
const $$createType5 = $models.RepoInfo.createFrom;
const $$createType6 = $models.RawDiffResult.createFrom;
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $models.CommitGraphResult.createFrom;
const $$createType9 = $models.ConflictSidesInfo.createFrom;
const $$createType10 = $models.ConflictedFile.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.GitVersion.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.MergeState.createFrom;
const $$createType15 = $models.ParentBranchResult.createFrom;
const $$createType16 = $models.CommitInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.CommitDetail.createFrom;
const $$createType19 = $models.StashEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.RepoStatus.createFrom;
