// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImageDiffService provides visual image diff comparison between git revisions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ImageDiff compares an image file between two revisions (or working tree).
 * 
 * Parameters:
 *   - repoPath: absolute path to the git repository root
 *   - filePath: path to the image file (relative to repo root or absolute)
 *   - oldRevision: commit hash, "HEAD", "HEAD~1", etc. Empty string = file didn't exist (added)
 *   - newRevision: commit hash, or empty string = use working tree version
 */
export function ImageDiff(repoPath: string, filePath: string, oldRevision: string, newRevision: string): $CancellablePromise<$models.ImageDiffResult> {
    return $Call.ByID(603761054, repoPath, filePath, oldRevision, newRevision).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImageDiffCommit compares an image in a commit against its parent.
 * Convenience method for viewing changes introduced by a specific commit.
 */
export function ImageDiffCommit(repoPath: string, filePath: string, commitHash: string): $CancellablePromise<$models.ImageDiffResult> {
    return $Call.ByID(2941118283, repoPath, filePath, commitHash).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImageDiffWorking compares the working tree version of an image against HEAD.
 * Convenience method for the common case of viewing uncommitted changes.
 */
export function ImageDiffWorking(repoPath: string, filePath: string): $CancellablePromise<$models.ImageDiffResult> {
    return $Call.ByID(2579508021, repoPath, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsImageFile checks if a file path has a supported image extension for diffing.
 * SVG is excluded since it's XML and better handled by text diff.
 */
export function IsImageFile(filePath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2072494783, filePath);
}

// Private type creation functions
const $$createType0 = $models.ImageDiffResult.createFrom;
