// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachToBus schedules a readiness check after each save. Only saves qualify:
 * every other mutation either cannot change what the destination would receive,
 * or is Finish itself moving the destination.
 */
export function AttachToBus(bus: $models.RepoEventBus | null): $CancellablePromise<void> {
    return $Call.ByID(1449981676, bus);
}

/**
 * CancelSession discards a review. It moves neither branch, and cancelling a
 * session that is already gone succeeds.
 */
export function CancelSession(sessionID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2679687464, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetachFromBus removes the bus subscription, if any.
 */
export function DetachFromBus(): $CancellablePromise<void> {
    return $Call.ByID(2471575149);
}

/**
 * FinishSession applies an already prepared result. It never rebuilds the
 * merge: if a valid result exists, that result is what gets applied.
 */
export function FinishSession(sessionID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2918716195, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSessionConflictResolutionData loads one conflicted file for the resolver.
 */
export function GetSessionConflictResolutionData(sessionID: string, filePath: string): $CancellablePromise<$models.ConflictResolutionData> {
    return $Call.ByID(3090228294, sessionID, filePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSessionConflicts returns the files this review is currently asking about.
 */
export function GetSessionConflicts(sessionID: string): $CancellablePromise<$models.SessionConflictSnapshot> {
    return $Call.ByID(4141193181, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSessionState returns the current state of one session. An unknown session
 * id yields an empty snapshot rather than an error, because a session can
 * legitimately disappear between the frontend reading it and asking about it.
 */
export function GetSessionState(sessionID: string): $CancellablePromise<$models.IntegrationSessionSnapshot> {
    return $Call.ByID(1897995979, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListSessions returns every session belonging to the repository containing
 * repoPath, including its linked worktrees.
 */
export function ListSessions(repoPath: string): $CancellablePromise<$models.IntegrationSessionSnapshot[]> {
    return $Call.ByID(4005078063, repoPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RecoverSessions reconciles persisted sessions with the worktrees and refs
 * they claim. Called once at startup. It never moves a ref.
 */
export function RecoverSessions(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2748400255).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveSessionConflictWithContent applies a fully composed file.
 */
export function ResolveSessionConflictWithContent(sessionID: string, filePath: string, resolutionToken: string, content: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3772647109, sessionID, filePath, resolutionToken, content).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveSessionConflictWithDecisions applies per-region choices to one file.
 */
export function ResolveSessionConflictWithDecisions(sessionID: string, filePath: string, resolutionToken: string, decisions: $models.ConflictDecision[]): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3376488127, sessionID, filePath, resolutionToken, decisions).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveSessionConflictWithSide keeps one whole version of the file.
 */
export function ResolveSessionConflictWithSide(sessionID: string, filePath: string, side: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2627696747, sessionID, filePath, side).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the Wails application reference for event emission.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(521708933, app);
}

/**
 * SetRepoEventBus lets a successful Finish announce that the repository moved,
 * so the conflict queue and the file watcher refresh.
 */
export function SetRepoEventBus(bus: $models.RepoEventBus | null): $CancellablePromise<void> {
    return $Call.ByID(3399731792, bus);
}

/**
 * SetSettings supplies the Developer Mode gate. Without it the scheduler stays
 * silent, which is the correct default for a feature that is still flagged.
 */
export function SetSettings(settings: $models.SettingsService | null): $CancellablePromise<void> {
    return $Call.ByID(2275590811, settings);
}

/**
 * UpdateFeatureFromDestination starts the update mutation. Session snapshots
 * are published through events and the session query methods.
 */
export function UpdateFeatureFromDestination(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3151023925, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.ConflictResolutionData.createFrom;
const $$createType2 = $models.SessionConflictSnapshot.createFrom;
const $$createType3 = $models.IntegrationSessionSnapshot.createFrom;
const $$createType4 = $Create.Array($$createType3);
