// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalBinService installs and manages user-level portable binaries.
 * On Windows, binaries are installed under %LOCALAPPDATA%\ControlZebra\bin.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnsurePortableToolchain installs portable Git, gh, and git-lfs in user-level storage.
 */
export function EnsurePortableToolchain(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2362914796).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * EnsurePortableToolchainIfNeeded installs missing portable tools for Windows.
 */
export function EnsurePortableToolchainIfNeeded(): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(692575198).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetStatus returns whether local managed binaries exist.
 */
export function GetStatus(): $CancellablePromise<$models.LocalBinStatus> {
    return $Call.ByID(1456327698).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1771178111, app);
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.LocalBinStatus.createFrom;
