// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * AppSettings contains application preferences
 */
export class AppSettings {
    /**
     * "dark", "light", "system"
     */
    "theme": string;

    /**
     * Last opened repository path
     */
    "lastRepoPath": string;

    /**
     * Recently opened folders (max 10)
     */
    "recentFolders": string[];

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("lastRepoPath" in $$source)) {
            this["lastRepoPath"] = "";
        }
        if (!("recentFolders" in $$source)) {
            this["recentFolders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentFolders" in $$parsedSource) {
            $$parsedSource["recentFolders"] = $$createField2_0($$parsedSource["recentFolders"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * BackgroundTaskConfig represents configuration for a background task
 */
export class BackgroundTaskConfig {
    "enabled": boolean;
    "intervalMinutes": number;

    /** Creates a new BackgroundTaskConfig instance. */
    constructor($$source: Partial<BackgroundTaskConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("intervalMinutes" in $$source)) {
            this["intervalMinutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackgroundTaskConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BackgroundTaskConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackgroundTaskConfig($$parsedSource as Partial<BackgroundTaskConfig>);
    }
}

/**
 * BackgroundTaskStatus represents the current status of a background task
 */
export class BackgroundTaskStatus {
    "taskType": BackgroundTaskType;
    "isRunning": boolean;
    "lastRun"?: time$0.Time | null;
    "lastResult"?: OperationResult | null;
    "nextRun"?: time$0.Time | null;
    "runCount": number;
    "errorCount": number;

    /** Creates a new BackgroundTaskStatus instance. */
    constructor($$source: Partial<BackgroundTaskStatus> = {}) {
        if (!("taskType" in $$source)) {
            this["taskType"] = BackgroundTaskType.$zero;
        }
        if (!("isRunning" in $$source)) {
            this["isRunning"] = false;
        }
        if (!("runCount" in $$source)) {
            this["runCount"] = 0;
        }
        if (!("errorCount" in $$source)) {
            this["errorCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackgroundTaskStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BackgroundTaskStatus {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lastResult" in $$parsedSource) {
            $$parsedSource["lastResult"] = $$createField3_0($$parsedSource["lastResult"]);
        }
        return new BackgroundTaskStatus($$parsedSource as Partial<BackgroundTaskStatus>);
    }
}

/**
 * BackgroundTaskType represents a type of background task
 */
export enum BackgroundTaskType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TaskFetchAll = "fetch_all",
    TaskLFSFetch = "lfs_fetch",
    TaskMaintenance = "maintenance",
};

/**
 * BranchConflictCheckResult contains the result of checking for conflicts between branches
 */
export class BranchConflictCheckResult {
    "hasConflicts": boolean;
    "conflictedFiles": ConflictedFile[];

    /**
     * The target branch to merge INTO (kept for backward compat)
     */
    "parentBranch": string;

    /**
     * The target branch to merge INTO
     */
    "targetBranch": string;

    /**
     * The source branch being merged
     */
    "sourceBranch": string;
    "success": boolean;
    "error"?: string;
    "message"?: string;

    /** Creates a new BranchConflictCheckResult instance. */
    constructor($$source: Partial<BranchConflictCheckResult> = {}) {
        if (!("hasConflicts" in $$source)) {
            this["hasConflicts"] = false;
        }
        if (!("conflictedFiles" in $$source)) {
            this["conflictedFiles"] = [];
        }
        if (!("parentBranch" in $$source)) {
            this["parentBranch"] = "";
        }
        if (!("targetBranch" in $$source)) {
            this["targetBranch"] = "";
        }
        if (!("sourceBranch" in $$source)) {
            this["sourceBranch"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchConflictCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchConflictCheckResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflictedFiles" in $$parsedSource) {
            $$parsedSource["conflictedFiles"] = $$createField1_0($$parsedSource["conflictedFiles"]);
        }
        return new BranchConflictCheckResult($$parsedSource as Partial<BranchConflictCheckResult>);
    }
}

/**
 * BranchInfo represents a git branch
 */
export class BranchInfo {
    "name": string;
    "isCurrent": boolean;
    "isRemote": boolean;

    /**
     * Remote tracking branch
     */
    "upstream"?: string;

    /** Creates a new BranchInfo instance. */
    constructor($$source: Partial<BranchInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }
        if (!("isRemote" in $$source)) {
            this["isRemote"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo($$parsedSource as Partial<BranchInfo>);
    }
}

/**
 * BranchList contains all branches in a repository
 */
export class BranchList {
    "current": string;
    "local": BranchInfo[];
    "remote": BranchInfo[];
    "hasError": boolean;
    "error"?: string;

    /** Creates a new BranchList instance. */
    constructor($$source: Partial<BranchList> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("local" in $$source)) {
            this["local"] = [];
        }
        if (!("remote" in $$source)) {
            this["remote"] = [];
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchList instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchList {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField1_0($$parsedSource["local"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField2_0($$parsedSource["remote"]);
        }
        return new BranchList($$parsedSource as Partial<BranchList>);
    }
}

/**
 * CommitDetail contains detailed information about a single commit
 */
export class CommitDetail {
    "hash": string;
    "shortHash": string;
    "message": string;

    /**
     * Full commit message body
     */
    "body"?: string;
    "author": string;
    "authorEmail": string;
    "date": string;
    "relativeDate": string;
    "parentHashes": string[];

    /**
     * Files changed in this commit
     */
    "files": CommitFileInfo[];

    /**
     * Overall stats
     */
    "stats": CommitStats;
    "hasError": boolean;
    "error"?: string;

    /** Creates a new CommitDetail instance. */
    constructor($$source: Partial<CommitDetail> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            this["relativeDate"] = "";
        }
        if (!("parentHashes" in $$source)) {
            this["parentHashes"] = [];
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new CommitStats());
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitDetail {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType8;
        const $$createField10_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parentHashes" in $$parsedSource) {
            $$parsedSource["parentHashes"] = $$createField8_0($$parsedSource["parentHashes"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField9_0($$parsedSource["files"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField10_0($$parsedSource["stats"]);
        }
        return new CommitDetail($$parsedSource as Partial<CommitDetail>);
    }
}

/**
 * CommitFileInfo represents a file changed in a commit
 */
export class CommitFileInfo {
    "path": string;

    /**
     * For renames
     */
    "oldPath"?: string;

    /**
     * "added", "modified", "deleted", "renamed"
     */
    "status": string;
    "additions": number;
    "deletions": number;

    /** Creates a new CommitFileInfo instance. */
    constructor($$source: Partial<CommitFileInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("additions" in $$source)) {
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitFileInfo($$parsedSource as Partial<CommitFileInfo>);
    }
}

/**
 * CommitGraphResult contains commits and branch information for graph visualization
 */
export class CommitGraphResult {
    "commits": GraphCommit[];

    /**
     * branch name -> commit hash
     */
    "branches": { [_: string]: string };

    /**
     * tag name -> commit hash
     */
    "tags": { [_: string]: string };
    "hasError": boolean;
    "error"?: string;

    /** Creates a new CommitGraphResult instance. */
    constructor($$source: Partial<CommitGraphResult> = {}) {
        if (!("commits" in $$source)) {
            this["commits"] = [];
        }
        if (!("branches" in $$source)) {
            this["branches"] = {};
        }
        if (!("tags" in $$source)) {
            this["tags"] = {};
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitGraphResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitGraphResult {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commits" in $$parsedSource) {
            $$parsedSource["commits"] = $$createField0_0($$parsedSource["commits"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField1_0($$parsedSource["branches"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new CommitGraphResult($$parsedSource as Partial<CommitGraphResult>);
    }
}

/**
 * CommitInfo represents a single commit
 */
export class CommitInfo {
    "hash": string;
    "shortHash": string;
    "message": string;
    "author": string;
    "authorEmail": string;
    "date": string;
    "relativeDate": string;

    /** Creates a new CommitInfo instance. */
    constructor($$source: Partial<CommitInfo> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            this["relativeDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo($$parsedSource as Partial<CommitInfo>);
    }
}

/**
 * CommitStats contains overall statistics for a commit
 */
export class CommitStats {
    "filesChanged": number;
    "additions": number;
    "deletions": number;

    /** Creates a new CommitStats instance. */
    constructor($$source: Partial<CommitStats> = {}) {
        if (!("filesChanged" in $$source)) {
            this["filesChanged"] = 0;
        }
        if (!("additions" in $$source)) {
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitStats instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitStats($$parsedSource as Partial<CommitStats>);
    }
}

/**
 * ConflictCommitInfo contains minimal commit info for conflict resolution display
 */
export class ConflictCommitInfo {
    "hash": string;
    "author": string;
    "date": string;
    "message": string;

    /** Creates a new ConflictCommitInfo instance. */
    constructor($$source: Partial<ConflictCommitInfo> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictCommitInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictCommitInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictCommitInfo($$parsedSource as Partial<ConflictCommitInfo>);
    }
}

/**
 * ConflictSidesInfo contains commit info for both sides of a conflict
 */
export class ConflictSidesInfo {
    /**
     * HEAD - your local changes
     */
    "ours": ConflictCommitInfo;

    /**
     * The incoming branch
     */
    "theirs": ConflictCommitInfo;
    "success": boolean;
    "error"?: string;

    /** Creates a new ConflictSidesInfo instance. */
    constructor($$source: Partial<ConflictSidesInfo> = {}) {
        if (!("ours" in $$source)) {
            this["ours"] = (new ConflictCommitInfo());
        }
        if (!("theirs" in $$source)) {
            this["theirs"] = (new ConflictCommitInfo());
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictSidesInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictSidesInfo {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ours" in $$parsedSource) {
            $$parsedSource["ours"] = $$createField0_0($$parsedSource["ours"]);
        }
        if ("theirs" in $$parsedSource) {
            $$parsedSource["theirs"] = $$createField1_0($$parsedSource["theirs"]);
        }
        return new ConflictSidesInfo($$parsedSource as Partial<ConflictSidesInfo>);
    }
}

/**
 * ConflictedFile represents a file with merge conflicts
 */
export class ConflictedFile {
    "path": string;

    /**
     * "both-modified", "deleted-by-us", "deleted-by-them", "both-added"
     */
    "status": string;

    /** Creates a new ConflictedFile instance. */
    constructor($$source: Partial<ConflictedFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictedFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictedFile($$parsedSource as Partial<ConflictedFile>);
    }
}

/**
 * CustomLFSGroup represents a user-defined LFS extension group
 */
export class CustomLFSGroup {
    "id": string;
    "name": string;

    /**
     * Tailwind color class like "text-cyan-400"
     */
    "color": string;

    /**
     * e.g., [".bin", ".dat"]
     */
    "extensions": string[];

    /**
     * Optional description
     */
    "description": string;

    /** Creates a new CustomLFSGroup instance. */
    constructor($$source: Partial<CustomLFSGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomLFSGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomLFSGroup {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField3_0($$parsedSource["extensions"]);
        }
        return new CustomLFSGroup($$parsedSource as Partial<CustomLFSGroup>);
    }
}

/**
 * CustomLFSGroupsData contains all custom LFS groups
 */
export class CustomLFSGroupsData {
    "groups": CustomLFSGroup[];

    /** Creates a new CustomLFSGroupsData instance. */
    constructor($$source: Partial<CustomLFSGroupsData> = {}) {
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomLFSGroupsData instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomLFSGroupsData {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        return new CustomLFSGroupsData($$parsedSource as Partial<CustomLFSGroupsData>);
    }
}

/**
 * DirectoryContents contains the contents of a directory
 */
export class DirectoryContents {
    "path": string;
    "entries": FileEntry[];
    "error"?: string;
    "includeHidden": boolean;

    /** Creates a new DirectoryContents instance. */
    constructor($$source: Partial<DirectoryContents> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("includeHidden" in $$source)) {
            this["includeHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryContents instance from a string or object.
     */
    static createFrom($$source: any = {}): DirectoryContents {
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new DirectoryContents($$parsedSource as Partial<DirectoryContents>);
    }
}

/**
 * ExportLFSGroupsResult contains the result of an export operation
 */
export class ExportLFSGroupsResult {
    "success": boolean;
    "path"?: string;
    "error"?: string;

    /** Creates a new ExportLFSGroupsResult instance. */
    constructor($$source: Partial<ExportLFSGroupsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportLFSGroupsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportLFSGroupsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportLFSGroupsResult($$parsedSource as Partial<ExportLFSGroupsResult>);
    }
}

/**
 * FetchSettings contains settings for git fetch operations
 */
export class FetchSettings {
    /**
     * FetchAllRemotes fetches from all remotes (--all flag)
     */
    "fetchAllRemotes": boolean;

    /**
     * PruneStaleBranches removes stale remote-tracking branches (--prune flag)
     */
    "pruneStaleBranches": boolean;

    /**
     * FetchTags fetches tags (--tags flag)
     */
    "fetchTags": boolean;

    /** Creates a new FetchSettings instance. */
    constructor($$source: Partial<FetchSettings> = {}) {
        if (!("fetchAllRemotes" in $$source)) {
            this["fetchAllRemotes"] = false;
        }
        if (!("pruneStaleBranches" in $$source)) {
            this["pruneStaleBranches"] = false;
        }
        if (!("fetchTags" in $$source)) {
            this["fetchTags"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FetchSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): FetchSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FetchSettings($$parsedSource as Partial<FetchSettings>);
    }
}

/**
 * FileEntry represents a file or directory in the file system
 */
export class FileEntry {
    "name": string;
    "path": string;
    "isDirectory": boolean;
    "size": number;
    "extension": string;

    /**
     * Unix timestamp in milliseconds
     */
    "modTime": number;
    "isHidden": boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDirectory" in $$source)) {
            this["isDirectory"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

/**
 * FileStatus represents the status of a changed file
 */
export class FileStatus {
    "path": string;
    "name": string;

    /**
     * "added", "modified", "deleted", "renamed", "untracked"
     */
    "status": string;

    /** Creates a new FileStatus instance. */
    constructor($$source: Partial<FileStatus> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): FileStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileStatus($$parsedSource as Partial<FileStatus>);
    }
}

/**
 * GitHubAuthResult represents the result of an auth operation
 */
export class GitHubAuthResult {
    "success": boolean;
    "message"?: string;
    "error"?: string;

    /** Creates a new GitHubAuthResult instance. */
    constructor($$source: Partial<GitHubAuthResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubAuthResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubAuthResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubAuthResult($$parsedSource as Partial<GitHubAuthResult>);
    }
}

/**
 * GitHubAuthStatus represents the authentication status for GitHub
 */
export class GitHubAuthStatus {
    "loggedIn": boolean;
    "username"?: string;

    /**
     * "user" or "org"
     */
    "accountType"?: string;

    /**
     * "https" or "ssh"
     */
    "protocol"?: string;

    /**
     * e.g., "github.com"
     */
    "host"?: string;

    /**
     * Masked or partial token
     */
    "token"?: string;

    /**
     * Token scopes
     */
    "scopes"?: string;
    "error"?: string;

    /** Creates a new GitHubAuthStatus instance. */
    constructor($$source: Partial<GitHubAuthStatus> = {}) {
        if (!("loggedIn" in $$source)) {
            this["loggedIn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubAuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubAuthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubAuthStatus($$parsedSource as Partial<GitHubAuthStatus>);
    }
}

/**
 * GitHubCloneResult represents the result of cloning a repository
 */
export class GitHubCloneResult {
    "success": boolean;

    /**
     * Local path where repo was cloned
     */
    "cloneDir"?: string;
    "error"?: string;

    /** Creates a new GitHubCloneResult instance. */
    constructor($$source: Partial<GitHubCloneResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubCloneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubCloneResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubCloneResult($$parsedSource as Partial<GitHubCloneResult>);
    }
}

/**
 * GitHubDeviceFlowResult represents the device flow authentication state
 */
export class GitHubDeviceFlowResult {
    "success": boolean;

    /**
     * The one-time code user needs to enter
     */
    "userCode"?: string;

    /**
     * URL to visit for authentication
     */
    "verificationUrl"?: string;
    "error"?: string;

    /** Creates a new GitHubDeviceFlowResult instance. */
    constructor($$source: Partial<GitHubDeviceFlowResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubDeviceFlowResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubDeviceFlowResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubDeviceFlowResult($$parsedSource as Partial<GitHubDeviceFlowResult>);
    }
}

/**
 * GitHubOrganization represents a GitHub organization
 */
export class GitHubOrganization {
    /**
     * Organization slug/name
     */
    "login": string;

    /**
     * Display name
     */
    "name": string;

    /**
     * Organization description
     */
    "description": string;

    /** Creates a new GitHubOrganization instance. */
    constructor($$source: Partial<GitHubOrganization> = {}) {
        if (!("login" in $$source)) {
            this["login"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubOrganization instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubOrganization {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubOrganization($$parsedSource as Partial<GitHubOrganization>);
    }
}

/**
 * GitHubOrganizationsResult represents the result of listing organizations
 */
export class GitHubOrganizationsResult {
    "success": boolean;

    /**
     * The authenticated user's username
     */
    "username": string;

    /**
     * Organizations the user belongs to
     */
    "organizations": GitHubOrganization[];
    "error"?: string;

    /** Creates a new GitHubOrganizationsResult instance. */
    constructor($$source: Partial<GitHubOrganizationsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("organizations" in $$source)) {
            this["organizations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubOrganizationsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubOrganizationsResult {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("organizations" in $$parsedSource) {
            $$parsedSource["organizations"] = $$createField2_0($$parsedSource["organizations"]);
        }
        return new GitHubOrganizationsResult($$parsedSource as Partial<GitHubOrganizationsResult>);
    }
}

/**
 * GitHubRepo represents a GitHub repository
 */
export class GitHubRepo {
    "name": string;

    /**
     * owner/repo format
     */
    "fullName": string;
    "description": string;
    "url": string;
    "sshUrl": string;
    "cloneUrl": string;
    "private": boolean;
    "fork": boolean;
    "archived": boolean;
    "defaultBranch": string;
    "language": string;
    "stargazersCount": number;
    "forksCount": number;
    "updatedAt": string;
    "createdAt": string;

    /** Creates a new GitHubRepo instance. */
    constructor($$source: Partial<GitHubRepo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("fullName" in $$source)) {
            this["fullName"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("sshUrl" in $$source)) {
            this["sshUrl"] = "";
        }
        if (!("cloneUrl" in $$source)) {
            this["cloneUrl"] = "";
        }
        if (!("private" in $$source)) {
            this["private"] = false;
        }
        if (!("fork" in $$source)) {
            this["fork"] = false;
        }
        if (!("archived" in $$source)) {
            this["archived"] = false;
        }
        if (!("defaultBranch" in $$source)) {
            this["defaultBranch"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("stargazersCount" in $$source)) {
            this["stargazersCount"] = 0;
        }
        if (!("forksCount" in $$source)) {
            this["forksCount"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubRepo instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubRepo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubRepo($$parsedSource as Partial<GitHubRepo>);
    }
}

/**
 * GitHubRepoCreateOptions contains options for creating a new repository
 */
export class GitHubRepoCreateOptions {
    "name": string;
    "description"?: string;
    "private": boolean;

    /**
     * Clone the repo after creation
     */
    "clone": boolean;

    /**
     * Path to clone to (if Clone is true)
     */
    "clonePath": string;

    /**
     * Initialize with README
     */
    "addReadme": boolean;

    /**
     * .gitignore template name
     */
    "gitIgnore": string;

    /**
     * License template name
     */
    "license": string;

    /** Creates a new GitHubRepoCreateOptions instance. */
    constructor($$source: Partial<GitHubRepoCreateOptions> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("private" in $$source)) {
            this["private"] = false;
        }
        if (!("clone" in $$source)) {
            this["clone"] = false;
        }
        if (!("clonePath" in $$source)) {
            this["clonePath"] = "";
        }
        if (!("addReadme" in $$source)) {
            this["addReadme"] = false;
        }
        if (!("gitIgnore" in $$source)) {
            this["gitIgnore"] = "";
        }
        if (!("license" in $$source)) {
            this["license"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubRepoCreateOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubRepoCreateOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubRepoCreateOptions($$parsedSource as Partial<GitHubRepoCreateOptions>);
    }
}

/**
 * GitHubRepoCreateResult represents the result of creating a repository
 */
export class GitHubRepoCreateResult {
    "success": boolean;
    "repo"?: GitHubRepo;

    /**
     * Local path if cloned
     */
    "cloneDir"?: string;
    "error"?: string;

    /** Creates a new GitHubRepoCreateResult instance. */
    constructor($$source: Partial<GitHubRepoCreateResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubRepoCreateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubRepoCreateResult {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repo" in $$parsedSource) {
            $$parsedSource["repo"] = $$createField1_0($$parsedSource["repo"]);
        }
        return new GitHubRepoCreateResult($$parsedSource as Partial<GitHubRepoCreateResult>);
    }
}

/**
 * GitHubRepoListResult represents the result of listing repositories
 */
export class GitHubRepoListResult {
    "success": boolean;
    "repos": GitHubRepo[];
    "error"?: string;

    /** Creates a new GitHubRepoListResult instance. */
    constructor($$source: Partial<GitHubRepoListResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("repos" in $$source)) {
            this["repos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubRepoListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubRepoListResult {
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repos" in $$parsedSource) {
            $$parsedSource["repos"] = $$createField1_0($$parsedSource["repos"]);
        }
        return new GitHubRepoListResult($$parsedSource as Partial<GitHubRepoListResult>);
    }
}

/**
 * GitRemoteInfo contains information about a git remote
 */
export class GitRemoteInfo {
    "name": string;
    "fetchUrl": string;
    "pushUrl": string;

    /** Creates a new GitRemoteInfo instance. */
    constructor($$source: Partial<GitRemoteInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("fetchUrl" in $$source)) {
            this["fetchUrl"] = "";
        }
        if (!("pushUrl" in $$source)) {
            this["pushUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitRemoteInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GitRemoteInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitRemoteInfo($$parsedSource as Partial<GitRemoteInfo>);
    }
}

/**
 * GitVersion represents parsed git version
 */
export class GitVersion {
    "Major": number;
    "Minor": number;
    "Patch": number;

    /** Creates a new GitVersion instance. */
    constructor($$source: Partial<GitVersion> = {}) {
        if (!("Major" in $$source)) {
            this["Major"] = 0;
        }
        if (!("Minor" in $$source)) {
            this["Minor"] = 0;
        }
        if (!("Patch" in $$source)) {
            this["Patch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): GitVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitVersion($$parsedSource as Partial<GitVersion>);
    }
}

/**
 * GraphCommit represents a commit with parent references for graph visualization
 */
export class GraphCommit {
    "hash": string;
    "shortHash": string;
    "message": string;
    "author": string;
    "authorEmail": string;
    "date": string;
    "relativeDate": string;

    /**
     * Parent commit hashes
     */
    "parents": string[];

    /**
     * Branch and tag refs pointing to this commit
     */
    "refs": string[];

    /** Creates a new GraphCommit instance. */
    constructor($$source: Partial<GraphCommit> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("relativeDate" in $$source)) {
            this["relativeDate"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }
        if (!("refs" in $$source)) {
            this["refs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphCommit instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphCommit {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField7_0($$parsedSource["parents"]);
        }
        if ("refs" in $$parsedSource) {
            $$parsedSource["refs"] = $$createField8_0($$parsedSource["refs"]);
        }
        return new GraphCommit($$parsedSource as Partial<GraphCommit>);
    }
}

/**
 * ImportLFSGroupsResult contains the result of an import operation
 */
export class ImportLFSGroupsResult {
    "success": boolean;
    "importedCount": number;
    "error"?: string;

    /** Creates a new ImportLFSGroupsResult instance. */
    constructor($$source: Partial<ImportLFSGroupsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("importedCount" in $$source)) {
            this["importedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportLFSGroupsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportLFSGroupsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportLFSGroupsResult($$parsedSource as Partial<ImportLFSGroupsResult>);
    }
}

/**
 * LFSFileStatus represents the LFS status of a file
 */
export class LFSFileStatus {
    "path": string;

    /**
     * "lfs" for LFS-tracked, "git" for regular
     */
    "status": string;

    /**
     * Human-readable size
     */
    "size": string;

    /**
     * True if file is uploaded to remote
     */
    "uploaded": boolean;

    /** Creates a new LFSFileStatus instance. */
    constructor($$source: Partial<LFSFileStatus> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = "";
        }
        if (!("uploaded" in $$source)) {
            this["uploaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSFileStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LFSFileStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSFileStatus($$parsedSource as Partial<LFSFileStatus>);
    }
}

/**
 * LFSInfo contains basic information about LFS status in a repo
 */
export class LFSInfo {
    "enabled": boolean;
    "version"?: string;
    "hasError": boolean;
    "error"?: string;

    /** Creates a new LFSInfo instance. */
    constructor($$source: Partial<LFSInfo> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LFSInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSInfo($$parsedSource as Partial<LFSInfo>);
    }
}

/**
 * LFSLock represents a locked file in Git LFS
 */
export class LFSLock {
    "path": string;
    "owner": string;
    "id": string;

    /**
     * Timestamp
     */
    "locked": string;

    /** Creates a new LFSLock instance. */
    constructor($$source: Partial<LFSLock> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSLock instance from a string or object.
     */
    static createFrom($$source: any = {}): LFSLock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSLock($$parsedSource as Partial<LFSLock>);
    }
}

/**
 * LFSSettings contains LFS-specific repository settings
 */
export class LFSSettings {
    /**
     * AutoFetch enables automatic LFS fetch for recent work
     */
    "autoFetch": boolean;

    /**
     * FetchRecentDays is the number of days to consider for "recent" work (git lfs fetch --recent)
     */
    "fetchRecentDays": number;

    /**
     * AutoPrune enables automatic pruning of old LFS objects
     */
    "autoPrune": boolean;

    /**
     * PruneKeepDays is the number of days to keep LFS objects before pruning
     */
    "pruneKeepDays": number;

    /** Creates a new LFSSettings instance. */
    constructor($$source: Partial<LFSSettings> = {}) {
        if (!("autoFetch" in $$source)) {
            this["autoFetch"] = false;
        }
        if (!("fetchRecentDays" in $$source)) {
            this["fetchRecentDays"] = 0;
        }
        if (!("autoPrune" in $$source)) {
            this["autoPrune"] = false;
        }
        if (!("pruneKeepDays" in $$source)) {
            this["pruneKeepDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LFSSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): LFSSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LFSSettings($$parsedSource as Partial<LFSSettings>);
    }
}

/**
 * LockFileInfo contains information about Git lock files in the repository
 */
export class LockFileInfo {
    "indexLockExists": boolean;
    "indexLockPath": string;
    "error"?: string;

    /** Creates a new LockFileInfo instance. */
    constructor($$source: Partial<LockFileInfo> = {}) {
        if (!("indexLockExists" in $$source)) {
            this["indexLockExists"] = false;
        }
        if (!("indexLockPath" in $$source)) {
            this["indexLockPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LockFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LockFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LockFileInfo($$parsedSource as Partial<LockFileInfo>);
    }
}

/**
 * MaintenanceSettings contains settings for git maintenance operations
 */
export class MaintenanceSettings {
    /**
     * CommitGraph enables commit-graph maintenance task
     */
    "commitGraph": boolean;

    /**
     * PackRefs enables pack-refs maintenance task
     */
    "packRefs": boolean;

    /**
     * LooseObjects enables loose-objects maintenance task
     */
    "looseObjects": boolean;

    /** Creates a new MaintenanceSettings instance. */
    constructor($$source: Partial<MaintenanceSettings> = {}) {
        if (!("commitGraph" in $$source)) {
            this["commitGraph"] = false;
        }
        if (!("packRefs" in $$source)) {
            this["packRefs"] = false;
        }
        if (!("looseObjects" in $$source)) {
            this["looseObjects"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MaintenanceSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): MaintenanceSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MaintenanceSettings($$parsedSource as Partial<MaintenanceSettings>);
    }
}

/**
 * MergeOptions contains options for StartMergeWithOptions
 */
export class MergeOptions {
    /**
     * If true, uses --squash for a squash merge
     */
    "squash": boolean;

    /** Creates a new MergeOptions instance. */
    constructor($$source: Partial<MergeOptions> = {}) {
        if (!("squash" in $$source)) {
            this["squash"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeOptions($$parsedSource as Partial<MergeOptions>);
    }
}

/**
 * MergeState represents the current repository operation state.
 * Extended to detect all common "stuck" states that can confuse users.
 * Priority for display: Locked > Merge > Cherry-Pick > Revert > Bisect > AM > Rebase (abort-only) > Detached HEAD
 * Note: Rebase is detected for abort purposes only - users should abort and use merge workflow instead.
 */
export class MergeState {
    /**
     * Core merge state
     */
    "inMerge": boolean;

    /**
     * Detected for abort only - rebase workflow is deprecated
     */
    "inRebase": boolean;
    "hasConflicts": boolean;

    /**
     * Merge commit message if available
     */
    "message"?: string;

    /**
     * Additional stuck states
     * .git/CHERRY_PICK_HEAD exists
     */
    "inCherryPick": boolean;

    /**
     * .git/REVERT_HEAD exists
     */
    "inRevert": boolean;

    /**
     * .git/BISECT_LOG exists
     */
    "inBisect": boolean;

    /**
     * .git/rebase-apply/applying exists
     */
    "inAM": boolean;

    /**
     * HEAD points to commit hash, not branch
     */
    "isDetached": boolean;

    /**
     * .git/index.lock exists (stale lock)
     */
    "hasLockFile": boolean;

    /**
     * Additional context
     * Commit hash when detached
     */
    "detachedAt"?: string;

    /**
     * List of lock files found
     */
    "lockFiles"?: string[];

    /**
     * Primary stuck state type for UI
     */
    "stuckType"?: string;

    /**
     * User-friendly explanation
     */
    "userMessage"?: string;

    /** Creates a new MergeState instance. */
    constructor($$source: Partial<MergeState> = {}) {
        if (!("inMerge" in $$source)) {
            this["inMerge"] = false;
        }
        if (!("inRebase" in $$source)) {
            this["inRebase"] = false;
        }
        if (!("hasConflicts" in $$source)) {
            this["hasConflicts"] = false;
        }
        if (!("inCherryPick" in $$source)) {
            this["inCherryPick"] = false;
        }
        if (!("inRevert" in $$source)) {
            this["inRevert"] = false;
        }
        if (!("inBisect" in $$source)) {
            this["inBisect"] = false;
        }
        if (!("inAM" in $$source)) {
            this["inAM"] = false;
        }
        if (!("isDetached" in $$source)) {
            this["isDetached"] = false;
        }
        if (!("hasLockFile" in $$source)) {
            this["hasLockFile"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeState instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeState {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lockFiles" in $$parsedSource) {
            $$parsedSource["lockFiles"] = $$createField11_0($$parsedSource["lockFiles"]);
        }
        return new MergeState($$parsedSource as Partial<MergeState>);
    }
}

/**
 * OpenFileResult contains the result of opening a file
 */
export class OpenFileResult {
    "success": boolean;
    "error"?: string;

    /** Creates a new OpenFileResult instance. */
    constructor($$source: Partial<OpenFileResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileResult($$parsedSource as Partial<OpenFileResult>);
    }
}

/**
 * OpenFolderDialogResult contains the result of an open folder dialog
 */
export class OpenFolderDialogResult {
    "path": string;
    "selected": boolean;
    "error"?: string;

    /** Creates a new OpenFolderDialogResult instance. */
    constructor($$source: Partial<OpenFolderDialogResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFolderDialogResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenFolderDialogResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFolderDialogResult($$parsedSource as Partial<OpenFolderDialogResult>);
    }
}

/**
 * OperationResult represents the result of a git operation
 */
export class OperationResult {
    "success": boolean;
    "message": string;
    "error"?: string;

    /** Creates a new OperationResult instance. */
    constructor($$source: Partial<OperationResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationResult($$parsedSource as Partial<OperationResult>);
    }
}

/**
 * ParentBranchResult contains the detected parent branch information
 */
export class ParentBranchResult {
    "parentBranch": string;

    /**
     * "upstream", "merge-base", "default", or "none"
     */
    "source": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new ParentBranchResult instance. */
    constructor($$source: Partial<ParentBranchResult> = {}) {
        if (!("parentBranch" in $$source)) {
            this["parentBranch"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParentBranchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ParentBranchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParentBranchResult($$parsedSource as Partial<ParentBranchResult>);
    }
}

/**
 * PresetPattern represents a preset LFS tracking pattern
 */
export class PresetPattern {
    "pattern": string;
    "description": string;

    /**
     * e.g., "industrial", "media", "documents"
     */
    "category": string;

    /** Creates a new PresetPattern instance. */
    constructor($$source: Partial<PresetPattern> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetPattern instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetPattern {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetPattern($$parsedSource as Partial<PresetPattern>);
    }
}

/**
 * ProtectedBranchSettings contains settings for protected branches
 */
export class ProtectedBranchSettings {
    /**
     * ProtectedBranches is a list of branch names that should be protected
     */
    "protectedBranches": string[];

    /**
     * WarnOnDirectCommit warns when committing directly to protected branches
     */
    "warnOnDirectCommit": boolean;

    /**
     * RequireConfirmation requires confirmation for operations on protected branches
     */
    "requireConfirmation": boolean;

    /** Creates a new ProtectedBranchSettings instance. */
    constructor($$source: Partial<ProtectedBranchSettings> = {}) {
        if (!("protectedBranches" in $$source)) {
            this["protectedBranches"] = [];
        }
        if (!("warnOnDirectCommit" in $$source)) {
            this["warnOnDirectCommit"] = false;
        }
        if (!("requireConfirmation" in $$source)) {
            this["requireConfirmation"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtectedBranchSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtectedBranchSettings {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("protectedBranches" in $$parsedSource) {
            $$parsedSource["protectedBranches"] = $$createField0_0($$parsedSource["protectedBranches"]);
        }
        return new ProtectedBranchSettings($$parsedSource as Partial<ProtectedBranchSettings>);
    }
}

/**
 * RawDiffResult contains raw unified diff text for react-diff-view parsing
 */
export class RawDiffResult {
    "path": string;
    "oldPath"?: string;

    /**
     * "added", "modified", "deleted", "renamed"
     */
    "status": string;
    "binary": boolean;

    /**
     * Raw unified diff text
     */
    "rawDiff": string;
    "hasError": boolean;
    "error"?: string;

    /** Creates a new RawDiffResult instance. */
    constructor($$source: Partial<RawDiffResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("rawDiff" in $$source)) {
            this["rawDiff"] = "";
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RawDiffResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RawDiffResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RawDiffResult($$parsedSource as Partial<RawDiffResult>);
    }
}

/**
 * ReadTextFileResult contains the result of reading a text file
 */
export class ReadTextFileResult {
    "success": boolean;
    "content"?: string;
    "error"?: string;

    /** Creates a new ReadTextFileResult instance. */
    constructor($$source: Partial<ReadTextFileResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadTextFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadTextFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadTextFileResult($$parsedSource as Partial<ReadTextFileResult>);
    }
}

/**
 * RecoveryDiagnostics contains information about the repository state
 */
export class RecoveryDiagnostics {
    "isValidRepo": boolean;
    "hasMergeConflict": boolean;
    "hasRebaseInProgress": boolean;
    "hasCherryPickInProgress": boolean;
    "hasRevertInProgress": boolean;
    "hasBisectInProgress": boolean;
    "hasAMInProgress": boolean;
    "isDetachedHead": boolean;
    "currentBranch": string;
    "hasStaleLocks": boolean;
    "staleLockFiles": string[];
    "hasUncommittedChanges": boolean;
    "unpushedCommits": number;
    "hasCorruptedObjects": boolean;
    "issues": string[];
    "suggestions": string[];

    /** Creates a new RecoveryDiagnostics instance. */
    constructor($$source: Partial<RecoveryDiagnostics> = {}) {
        if (!("isValidRepo" in $$source)) {
            this["isValidRepo"] = false;
        }
        if (!("hasMergeConflict" in $$source)) {
            this["hasMergeConflict"] = false;
        }
        if (!("hasRebaseInProgress" in $$source)) {
            this["hasRebaseInProgress"] = false;
        }
        if (!("hasCherryPickInProgress" in $$source)) {
            this["hasCherryPickInProgress"] = false;
        }
        if (!("hasRevertInProgress" in $$source)) {
            this["hasRevertInProgress"] = false;
        }
        if (!("hasBisectInProgress" in $$source)) {
            this["hasBisectInProgress"] = false;
        }
        if (!("hasAMInProgress" in $$source)) {
            this["hasAMInProgress"] = false;
        }
        if (!("isDetachedHead" in $$source)) {
            this["isDetachedHead"] = false;
        }
        if (!("currentBranch" in $$source)) {
            this["currentBranch"] = "";
        }
        if (!("hasStaleLocks" in $$source)) {
            this["hasStaleLocks"] = false;
        }
        if (!("staleLockFiles" in $$source)) {
            this["staleLockFiles"] = [];
        }
        if (!("hasUncommittedChanges" in $$source)) {
            this["hasUncommittedChanges"] = false;
        }
        if (!("unpushedCommits" in $$source)) {
            this["unpushedCommits"] = 0;
        }
        if (!("hasCorruptedObjects" in $$source)) {
            this["hasCorruptedObjects"] = false;
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }
        if (!("suggestions" in $$source)) {
            this["suggestions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecoveryDiagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): RecoveryDiagnostics {
        const $$createField10_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("staleLockFiles" in $$parsedSource) {
            $$parsedSource["staleLockFiles"] = $$createField10_0($$parsedSource["staleLockFiles"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField14_0($$parsedSource["issues"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField15_0($$parsedSource["suggestions"]);
        }
        return new RecoveryDiagnostics($$parsedSource as Partial<RecoveryDiagnostics>);
    }
}

/**
 * ReflogEntry represents an entry from git reflog
 */
export class ReflogEntry {
    "hash": string;
    "shortHash": string;
    "action": string;
    "message": string;
    "timestamp": string;

    /** Creates a new ReflogEntry instance. */
    constructor($$source: Partial<ReflogEntry> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReflogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ReflogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReflogEntry($$parsedSource as Partial<ReflogEntry>);
    }
}

/**
 * RepoInfo contains basic information about a git repository
 */
export class RepoInfo {
    "path": string;
    "isRepo": boolean;
    "branch": string;
    "hasError": boolean;
    "error"?: string;

    /** Creates a new RepoInfo instance. */
    constructor($$source: Partial<RepoInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isRepo" in $$source)) {
            this["isRepo"] = false;
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoInfo($$parsedSource as Partial<RepoInfo>);
    }
}

/**
 * RepoStatus contains the current state of a repository
 */
export class RepoStatus {
    "branch": string;
    "ahead": number;
    "behind": number;
    "changedFiles": FileStatus[];
    "hasChanges": boolean;

    /**
     * true if branch has upstream tracking
     */
    "hasUpstream": boolean;

    /**
     * total commits on current branch (useful when no upstream)
     */
    "totalLocalCommits": number;
    "hasError": boolean;
    "error"?: string;

    /** Creates a new RepoStatus instance. */
    constructor($$source: Partial<RepoStatus> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("ahead" in $$source)) {
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            this["behind"] = 0;
        }
        if (!("changedFiles" in $$source)) {
            this["changedFiles"] = [];
        }
        if (!("hasChanges" in $$source)) {
            this["hasChanges"] = false;
        }
        if (!("hasUpstream" in $$source)) {
            this["hasUpstream"] = false;
        }
        if (!("totalLocalCommits" in $$source)) {
            this["totalLocalCommits"] = 0;
        }
        if (!("hasError" in $$source)) {
            this["hasError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoStatus {
        const $$createField3_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changedFiles" in $$parsedSource) {
            $$parsedSource["changedFiles"] = $$createField3_0($$parsedSource["changedFiles"]);
        }
        return new RepoStatus($$parsedSource as Partial<RepoStatus>);
    }
}

/**
 * RepositorySettings contains all repository-level settings
 */
export class RepositorySettings {
    /**
     * RepoPath is the absolute path to the repository
     */
    "repoPath": string;

    /**
     * RepoID is a unique identifier derived from the repo path
     */
    "repoId": string;

    /**
     * Background task configurations
     */
    "fetchTask": BackgroundTaskConfig;
    "lfsFetchTask": BackgroundTaskConfig;
    "maintenanceTask": BackgroundTaskConfig;

    /**
     * Detailed settings
     */
    "fetchSettings": FetchSettings;
    "lfsSettings": LFSSettings;
    "maintenanceSettings": MaintenanceSettings;
    "protectedBranches": ProtectedBranchSettings;

    /**
     * Metadata
     */
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new RepositorySettings instance. */
    constructor($$source: Partial<RepositorySettings> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("repoId" in $$source)) {
            this["repoId"] = "";
        }
        if (!("fetchTask" in $$source)) {
            this["fetchTask"] = (new BackgroundTaskConfig());
        }
        if (!("lfsFetchTask" in $$source)) {
            this["lfsFetchTask"] = (new BackgroundTaskConfig());
        }
        if (!("maintenanceTask" in $$source)) {
            this["maintenanceTask"] = (new BackgroundTaskConfig());
        }
        if (!("fetchSettings" in $$source)) {
            this["fetchSettings"] = (new FetchSettings());
        }
        if (!("lfsSettings" in $$source)) {
            this["lfsSettings"] = (new LFSSettings());
        }
        if (!("maintenanceSettings" in $$source)) {
            this["maintenanceSettings"] = (new MaintenanceSettings());
        }
        if (!("protectedBranches" in $$source)) {
            this["protectedBranches"] = (new ProtectedBranchSettings());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositorySettings instance from a string or object.
     */
    static createFrom($$source: any = {}): RepositorySettings {
        const $$createField2_0 = $$createType24;
        const $$createField3_0 = $$createType24;
        const $$createField4_0 = $$createType24;
        const $$createField5_0 = $$createType25;
        const $$createField6_0 = $$createType26;
        const $$createField7_0 = $$createType27;
        const $$createField8_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fetchTask" in $$parsedSource) {
            $$parsedSource["fetchTask"] = $$createField2_0($$parsedSource["fetchTask"]);
        }
        if ("lfsFetchTask" in $$parsedSource) {
            $$parsedSource["lfsFetchTask"] = $$createField3_0($$parsedSource["lfsFetchTask"]);
        }
        if ("maintenanceTask" in $$parsedSource) {
            $$parsedSource["maintenanceTask"] = $$createField4_0($$parsedSource["maintenanceTask"]);
        }
        if ("fetchSettings" in $$parsedSource) {
            $$parsedSource["fetchSettings"] = $$createField5_0($$parsedSource["fetchSettings"]);
        }
        if ("lfsSettings" in $$parsedSource) {
            $$parsedSource["lfsSettings"] = $$createField6_0($$parsedSource["lfsSettings"]);
        }
        if ("maintenanceSettings" in $$parsedSource) {
            $$parsedSource["maintenanceSettings"] = $$createField7_0($$parsedSource["maintenanceSettings"]);
        }
        if ("protectedBranches" in $$parsedSource) {
            $$parsedSource["protectedBranches"] = $$createField8_0($$parsedSource["protectedBranches"]);
        }
        return new RepositorySettings($$parsedSource as Partial<RepositorySettings>);
    }
}

/**
 * StashEntry represents a single stash entry
 */
export class StashEntry {
    "index": number;

    /**
     * e.g., "stash@{0}"
     */
    "name": string;

    /**
     * Stash message
     */
    "message": string;

    /**
     * Branch the stash was created on
     */
    "branch": string;

    /** Creates a new StashEntry instance. */
    constructor($$source: Partial<StashEntry> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StashEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StashEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StashEntry($$parsedSource as Partial<StashEntry>);
    }
}

/**
 * TerminalResult contains the result of terminal operations
 */
export class TerminalResult {
    "sessionId": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new TerminalResult instance. */
    constructor($$source: Partial<TerminalResult> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalResult($$parsedSource as Partial<TerminalResult>);
    }
}

/**
 * TrackedPattern represents a pattern tracked by Git LFS
 */
export class TrackedPattern {
    "pattern": string;

    /**
     * e.g., "filter=lfs diff=lfs merge=lfs -text"
     */
    "attributes"?: string;

    /** Creates a new TrackedPattern instance. */
    constructor($$source: Partial<TrackedPattern> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrackedPattern instance from a string or object.
     */
    static createFrom($$source: any = {}): TrackedPattern {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrackedPattern($$parsedSource as Partial<TrackedPattern>);
    }
}

/**
 * UserProfile contains git user configuration
 */
export class UserProfile {
    "name": string;
    "email": string;

    /** Creates a new UserProfile instance. */
    constructor($$source: Partial<UserProfile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): UserProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile($$parsedSource as Partial<UserProfile>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = OperationResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ConflictedFile.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = BranchInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = CommitFileInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = CommitStats.createFrom;
const $$createType10 = GraphCommit.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
const $$createType13 = ConflictCommitInfo.createFrom;
const $$createType14 = CustomLFSGroup.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = FileEntry.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = GitHubOrganization.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = GitHubRepo.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = FileStatus.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = BackgroundTaskConfig.createFrom;
const $$createType25 = FetchSettings.createFrom;
const $$createType26 = LFSSettings.createFrom;
const $$createType27 = MaintenanceSettings.createFrom;
const $$createType28 = ProtectedBranchSettings.createFrom;
