// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProgressService handles git operations with progress reporting
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PullWithProgress performs git pull with progress updates
 */
export function PullWithProgress(repoPath: string, operationID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2788985119, repoPath, operationID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PushWithProgress performs git push with progress updates
 */
export function PushWithProgress(repoPath: string, operationID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4172712624, repoPath, operationID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the Wails application reference for event emission
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3463078608, app);
}

/**
 * SyncWithProgress performs git pull + push with progress updates
 * For branches without an upstream, it skips pull and just pushes with --set-upstream
 * prune: if true, adds --prune to remove stale remote-tracking branches
 * tags: if true, adds --tags to fetch all tags
 */
export function SyncWithProgress(repoPath: string, operationID: string, prune: boolean, tags: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2296486007, repoPath, operationID, prune, tags).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
