// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RepositorySettingsService manages repository-level configuration and background tasks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortCherryPick aborts an in-progress cherry-pick
 */
export function AbortCherryPick(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(513082069, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AbortMerge aborts an in-progress merge
 */
export function AbortMerge(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1963077227, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearCredentialCache clears cached credentials
 */
export function ClearCredentialCache(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4114535611, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteSettings removes settings for a repository
 */
export function DeleteSettings(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(321219863, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DiagnoseRepository runs diagnostics on the repository to identify issues
 */
export function DiagnoseRepository(repoPath: string): $CancellablePromise<$models.RecoveryDiagnostics> {
    return $Call.ByID(2470451349, repoPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EnsureControlZebraDir creates the .controlzebra/ directory and ensures the
 * personal config file is gitignored. Call this during project initialisation.
 */
export function EnsureControlZebraDir(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3276428263, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FixRemoteURL updates the remote URL (useful when remote has moved or credentials changed)
 */
export function FixRemoteURL(repoPath: string, remoteName: string, newURL: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1910755015, repoPath, remoteName, newURL).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAllGitConfigs returns all local git config values for the repository
 */
export function GetAllGitConfigs(repoPath: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(4287591701, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetDefaultSettings returns the default settings for a new repository
 */
export function GetDefaultSettings(repoPath: string): $CancellablePromise<$models.RepositorySettings> {
    return $Call.ByID(2433052277, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGitConfig returns a git config value for the repository
 */
export function GetGitConfig(repoPath: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1643918023, repoPath, key);
}

/**
 * GetReflog returns recent reflog entries for recovery purposes
 */
export function GetReflog(repoPath: string, limit: number): $CancellablePromise<$models.ReflogEntry[]> {
    return $Call.ByID(2145591474, repoPath, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRemotes returns all remotes for a repository
 */
export function GetRemotes(repoPath: string): $CancellablePromise<$models.GitRemoteInfo[]> {
    return $Call.ByID(3735676250, repoPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSettings retrieves settings for a repository
 */
export function GetSettings(repoPath: string): $CancellablePromise<$models.RepositorySettings> {
    return $Call.ByID(1622511282, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTaskStatuses returns the current status of all background tasks
 */
export function GetTaskStatuses(): $CancellablePromise<{ [_ in string]?: $models.BackgroundTaskStatus | null }> {
    return $Call.ByID(4181591900).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ReadRepoLocalConfig reads the shared config (.controlzebra/config.json) from
 * the repository. This file is committed and shared with collaborators.
 * Returns a zero-value config if the file does not exist.
 */
export function ReadRepoLocalConfig(repoPath: string): $CancellablePromise<$models.RepoLocalConfig> {
    return $Call.ByID(1032641254, repoPath).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ReadRepoPersonalConfig reads the personal/machine-specific config
 * (.controlzebra/local.json) from the repository. This file is gitignored and
 * NOT committed. Returns a zero-value config if the file does not exist.
 */
export function ReadRepoPersonalConfig(repoPath: string): $CancellablePromise<$models.RepoPersonalConfig> {
    return $Call.ByID(1468831583, repoPath).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * RecoverFromDetachedHead creates a new branch from detached HEAD or switches to an existing branch
 */
export function RecoverFromDetachedHead(repoPath: string, newBranchName: string, switchToExisting: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1468557391, repoPath, newBranchName, switchToExisting).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RecoverToReflogEntry recovers the repository to a specific reflog entry
 */
export function RecoverToReflogEntry(repoPath: string, hash: string, createBranch: boolean, branchName: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3900879145, repoPath, hash, createBranch, branchName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RecreateRemote removes and re-adds a remote
 */
export function RecreateRemote(repoPath: string, remoteName: string, url: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3375817834, repoPath, remoteName, url).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RemoveStaleLocks removes stale lock files that may be blocking Git operations
 */
export function RemoveStaleLocks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(370009294, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RepairRepository attempts to repair common repository issues
 */
export function RepairRepository(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2192220352, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetHard performs a hard reset to a specific ref (use with caution)
 */
export function ResetHard(repoPath: string, ref: string, confirm: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1245348181, repoPath, ref, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResetToDefaults resets all settings for a repository to defaults
 */
export function ResetToDefaults(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4086126579, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RestartBackgroundTasks restarts all background tasks for a repository
 */
export function RestartBackgroundTasks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1786410722, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RunTaskNow runs a background task immediately
 */
export function RunTaskNow(repoPath: string, taskType: $models.BackgroundTaskType): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(362636249, repoPath, taskType).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings saves settings for a repository
 */
export function SaveSettings(settings: $models.RepositorySettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(294414573, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the application reference (called after app initialization)
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(499575534, app);
}

/**
 * SetGitConfig sets a git config value for the repository
 */
export function SetGitConfig(repoPath: string, key: string, value: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(868804395, repoPath, key, value).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetUpstreamBranch sets the upstream tracking branch
 */
export function SetUpstreamBranch(repoPath: string, remoteBranch: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(176924750, repoPath, remoteBranch).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StartBackgroundTasks starts background tasks for a repository
 */
export function StartBackgroundTasks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4221563179, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StashAndReset stashes current changes before resetting
 */
export function StashAndReset(repoPath: string, ref: string, stashMessage: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2959044426, repoPath, ref, stashMessage).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StopBackgroundTasks stops all background tasks for a repository
 */
export function StopBackgroundTasks(repoPath: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1389077597, repoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnsetGitConfig removes a git config value from the repository
 */
export function UnsetGitConfig(repoPath: string, key: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3545101820, repoPath, key).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateBackgroundTask updates the configuration for a specific background task
 */
export function UpdateBackgroundTask(repoPath: string, taskType: $models.BackgroundTaskType, config: $models.BackgroundTaskConfig): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3961703453, repoPath, taskType, config).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateFetchSettings updates fetch-related settings
 */
export function UpdateFetchSettings(repoPath: string, fetchSettings: $models.FetchSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(559173737, repoPath, fetchSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateLFSSettings updates LFS-related settings
 */
export function UpdateLFSSettings(repoPath: string, lfsSettings: $models.LFSSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3231604222, repoPath, lfsSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateMaintenanceSettings updates maintenance-related settings
 */
export function UpdateMaintenanceSettings(repoPath: string, maintenanceSettings: $models.MaintenanceSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(1654879214, repoPath, maintenanceSettings).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateProtectedBranches updates protected branch settings
 */
export function UpdateProtectedBranches(repoPath: string, protectedBranches: $models.ProtectedBranchSettings): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2757747210, repoPath, protectedBranches).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WriteRepoLocalConfig writes the shared config (.controlzebra/config.json) to
 * the repository. Creates the .controlzebra/ directory if it does not exist.
 */
export function WriteRepoLocalConfig(repoPath: string, config: $models.RepoLocalConfig): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3742543705, repoPath, config).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WriteRepoPersonalConfig writes the personal/machine-specific config
 * (.controlzebra/local.json) to the repository. Creates the .controlzebra/
 * directory if it does not exist. Also ensures .controlzebra/local.json is
 * listed in the repository's .gitignore so it is never committed.
 */
export function WriteRepoPersonalConfig(repoPath: string, config: $models.RepoPersonalConfig): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2316351710, repoPath, config).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.RecoveryDiagnostics.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.RepositorySettings.createFrom;
const $$createType4 = $models.ReflogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.GitRemoteInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.BackgroundTaskStatus.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = $models.RepoLocalConfig.createFrom;
const $$createType12 = $models.RepoPersonalConfig.createFrom;
