// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService manages app and user settings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRecentFolder adds a folder to the recent folders list
 * It moves the folder to the front if it already exists
 */
export function AddRecentFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(978828039, folderPath);
}

/**
 * ClearRecentFolders clears the recent folders list
 */
export function ClearRecentFolders(): $CancellablePromise<void> {
    return $Call.ByID(2439245746);
}

/**
 * EnsureIdentity checks that the repo has git user.name and user.email configured.
 * If either is missing from both local and global git config, it auto-sets from the
 * provided fallback values (typically from the Supabase login) into LOCAL repo config.
 * 
 * Priority (read):  local repo config > global config > fallback
 * Priority (write): only writes to local repo config, never touches global
 * 
 * This should be called whenever a repo is opened. The fallbackName and fallbackEmail
 * come from the authenticated ControlZebra user (Supabase session).
 */
export function EnsureIdentity(repoPath: string, fallbackName: string, fallbackEmail: string): $CancellablePromise<$models.DetectedIdentity> {
    return $Call.ByID(918403549, repoPath, fallbackName, fallbackEmail).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAppSettings returns the current app settings
 */
export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4098526243).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetRecentFolders returns the list of recently opened folders
 */
export function GetRecentFolders(): $CancellablePromise<string[]> {
    return $Call.ByID(4002401493).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetUserProfile returns the git user config (global or for a specific repo)
 * Uses concurrent goroutines to fetch name and email in parallel
 */
export function GetUserProfile(repoPath: string): $CancellablePromise<$models.UserProfile> {
    return $Call.ByID(1258519717, repoPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveAppSettings saves the app settings
 */
export function SaveAppSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3159081354, settings);
}

/**
 * SetApp sets the application reference (called after app initialization)
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1565004562, app);
}

/**
 * SetUserProfile sets the git user config
 */
export function SetUserProfile(repoPath: string, profile: $models.UserProfile, global: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3284937681, repoPath, profile, global).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DetectedIdentity.createFrom;
const $$createType1 = $models.AppSettings.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.UserProfile.createFrom;
const $$createType4 = $models.OperationResult.createFrom;
