// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService manages app and user settings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustomLFSGroup adds a new custom LFS group
 */
export function AddCustomLFSGroup(group: $models.CustomLFSGroup): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3930016361, group).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddRecentFolder adds a folder to the recent folders list
 * It moves the folder to the front if it already exists
 */
export function AddRecentFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(978828039, folderPath);
}

/**
 * ClearRecentFolders clears the recent folders list
 */
export function ClearRecentFolders(): $CancellablePromise<void> {
    return $Call.ByID(2439245746);
}

/**
 * DeleteCustomLFSGroup deletes a custom LFS group by ID
 */
export function DeleteCustomLFSGroup(groupID: string): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(4019406711, groupID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportCustomLFSGroups exports custom LFS groups to a JSON file
 */
export function ExportCustomLFSGroups(): $CancellablePromise<$models.ExportLFSGroupsResult> {
    return $Call.ByID(2748950067).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAppSettings returns the current app settings
 */
export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4098526243).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetCustomLFSGroups returns all custom LFS groups
 */
export function GetCustomLFSGroups(): $CancellablePromise<$models.CustomLFSGroupsData> {
    return $Call.ByID(1787134927).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRecentFolders returns the list of recently opened folders
 */
export function GetRecentFolders(): $CancellablePromise<string[]> {
    return $Call.ByID(4002401493).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetUserProfile returns the git user config (global or for a specific repo)
 * Uses concurrent goroutines to fetch name and email in parallel
 */
export function GetUserProfile(repoPath: string): $CancellablePromise<$models.UserProfile> {
    return $Call.ByID(1258519717, repoPath).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ImportCustomLFSGroups imports custom LFS groups from a JSON file
 */
export function ImportCustomLFSGroups(merge: boolean): $CancellablePromise<$models.ImportLFSGroupsResult> {
    return $Call.ByID(3112124302, merge).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SaveAppSettings saves the app settings
 */
export function SaveAppSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3159081354, settings);
}

/**
 * SaveCustomLFSGroups saves all custom LFS groups
 */
export function SaveCustomLFSGroups(data: $models.CustomLFSGroupsData): $CancellablePromise<void> {
    return $Call.ByID(2004902442, data);
}

/**
 * SetApp sets the application reference (called after app initialization)
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1565004562, app);
}

/**
 * SetUserProfile sets the git user config
 */
export function SetUserProfile(repoPath: string, profile: $models.UserProfile, global: boolean): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(3284937681, repoPath, profile, global).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateCustomLFSGroup updates an existing custom LFS group
 */
export function UpdateCustomLFSGroup(group: $models.CustomLFSGroup): $CancellablePromise<$models.OperationResult> {
    return $Call.ByID(2024044881, group).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.OperationResult.createFrom;
const $$createType1 = $models.ExportLFSGroupsResult.createFrom;
const $$createType2 = $models.AppSettings.createFrom;
const $$createType3 = $models.CustomLFSGroupsData.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.UserProfile.createFrom;
const $$createType6 = $models.ImportLFSGroupsResult.createFrom;
