// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages PTY-based terminal sessions
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseAllSessions terminates all terminal sessions
 */
export function CloseAllSessions(): $CancellablePromise<void> {
    return $Call.ByID(827019650);
}

/**
 * CloseSession terminates a terminal session
 */
export function CloseSession(sessionID: string): $CancellablePromise<$models.TerminalResult> {
    return $Call.ByID(1813883940, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateSession creates a new terminal session
 */
export function CreateSession(workingDir: string): $CancellablePromise<$models.TerminalResult> {
    return $Call.ByID(2029438780, workingDir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDefaultDirectory returns the default working directory
 */
export function GetDefaultDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3963419776);
}

/**
 * GetDefaultShell returns the default shell for the current OS
 */
export function GetDefaultShell(): $CancellablePromise<string> {
    return $Call.ByID(2342078297);
}

/**
 * ResizeTerminal resizes the PTY
 */
export function ResizeTerminal(sessionID: string, cols: number, rows: number): $CancellablePromise<$models.TerminalResult> {
    return $Call.ByID(912823420, sessionID, cols, rows).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetApp sets the Wails application reference for event emission
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3886079407, app);
}

/**
 * WriteInput sends input to the terminal session
 */
export function WriteInput(sessionID: string, data: string): $CancellablePromise<$models.TerminalResult> {
    return $Call.ByID(3132442769, sessionID, data).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TerminalResult.createFrom;
