// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes app-update functionality to the frontend.
 * It spawns the cz-updater sidecar binary for each operation and translates its
 * JSON output into a stable Wails event contract for the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate spawns `cz-updater check` and returns a stable typed result.
 */
export function CheckForUpdate(channel: string): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(2531457035, channel).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCurrentVersion returns the app's compiled version string.
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(3539201268);
}

/**
 * SetApp sets the Wails application reference for event emission.
 * Called after app initialization in main.go.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(485060246, app);
}

/**
 * StartUpdate checks, downloads, and hands off the update apply flow.
 */
export function StartUpdate(options: $models.StartUpdateOptions): $CancellablePromise<void> {
    return $Call.ByID(1472640686, options);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
