// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdaterService exposes auto-update functionality to the frontend.
 * It spawns the cz-updater sidecar binary for each operation and parses its
 * JSON output. Progress events are forwarded to the frontend via Wails events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate spawns `cz-updater apply` as a detached process.
 * The sidecar will wait for this app to exit, swap the binary, and relaunch.
 * After calling this, the frontend should quit the app gracefully.
 */
export function ApplyUpdate(stagedPath: string): $CancellablePromise<void> {
    return $Call.ByID(1551785272, stagedPath);
}

/**
 * CheckForUpdate spawns `cz-updater check` and returns update info.
 * Returns nil with no error if the app is already up to date.
 * Returns nil with an error if the check failed (network, parse, sidecar missing).
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(621776829).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndApply is a convenience method that downloads the update and
 * immediately applies it. The frontend should quit the app after this returns.
 */
export function DownloadAndApply(downloadURL: string, checksum: string): $CancellablePromise<void> {
    return $Call.ByID(3141818424, downloadURL, checksum);
}

/**
 * DownloadUpdate spawns `cz-updater download` with progress streaming.
 * Emits "updater:progress" Wails events as download advances.
 * Returns the path to the staged binary on success.
 */
export function DownloadUpdate(downloadURL: string, checksum: string): $CancellablePromise<string> {
    return $Call.ByID(2738667874, downloadURL, checksum);
}

/**
 * GetCurrentVersion returns the app's compiled version string.
 */
export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(1348627938);
}

/**
 * SetApp sets the Wails application reference for event emission.
 * Called after app initialization in main.go.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2939483556, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
